/* 0062 agg-hot (137) + 0069 swap-in fault path (88) + 0073 GLQuake flash residue (8 resolved duplicates + 89 picked), hot-first within each */
		*(.text..fast.generic_handle_domain_irq)	/* kernel/irq/irqdesc.o 22 B 54 samples */
		*(.text..fast.radix_tree_lookup)	/* lib/radix-tree.o 16 B 30 samples */
		*(.text..fast.handle_irq_desc)	/* kernel/irq/irqdesc.o 46 B 44 samples */
		*(.text..fast.riscv_clocksource_rdtime)	/* drivers/clocksource/timer-riscv.o 12 B 11 samples */
		*(.text..fast.fdget)	/* fs/file.o 14 B 10 samples */
		*(.text..fast.do_raw_spin_lock)	/* kernel/locking/spinlock.o 54 B 38 samples */
		*(.text..fast.__irq_resolve_mapping)	/* kernel/irq/irqdomain.o 76 B 45 samples */
		*(.text..fast.radix_tree_load_root)	/* lib/radix-tree.o 42 B 22 samples */
		*(.text..fast.riscv_intc_irq)	/* drivers/irqchip/irq-riscv-intc.o 76 B 29 samples */
		*(.text..fast.clic_writeb)	/* drivers/irqchip/irq-esp32s31-clic.o 52 B 18 samples */
		*(.text..fast.irq_can_handle)	/* kernel/irq/chip.o 26 B 9 samples */
		*(.text..fast.handle_percpu_devid_irq)	/* kernel/irq/chip.o 220 B 72 samples */
		*(.text..fast.__radix_tree_lookup)	/* lib/radix-tree.o 112 B 31 samples */
		*(.text..fast.esp32s31_clic_handle_irq)	/* drivers/irqchip/irq-esp32s31-clic.o 364 B 94 samples */
		*(.text..fast.put_prev_task_idle)	/* kernel/sched/build_policy.o 24 B 6 samples */
		*(.text..fast.list_lru_count_one)	/* mm/list_lru.o 20 B 5 samples */
		*(.text..fast.drm_crtc_handle_vblank)	/* drivers/gpu/drm/drm_vblank.o 16 B 4 samples */
		*(.text..fast.__kstat_incr_irqs_this_cpu.isra.0)	/* kernel/irq/chip.o 54 B 12 samples */
		*(.text..fast.rb_erase_linked)	/* lib/rbtree.o 56 B 12 samples */
		*(.text..fast.schedule_hrtimeout_range)	/* kernel/time/sleep_timeout.o 14 B 3 samples */
		*(.text..fast.mask_irq)	/* kernel/irq/chip.o 44 B 9 samples */
		*(.text..fast.riscv_timer_interrupt)	/* drivers/clocksource/timer-riscv.o 50 B 10 samples */
		*(.text..fast.put_timespec64)	/* kernel/time/time.o 48 B 9 samples */
		*(.text..fast.riscv_clock_event_stop)	/* drivers/clocksource/timer-riscv.o 40 B 7 samples */
		*(.text..fast.__riscv_isa_extension_available)	/* arch/riscv/kernel/cpufeature.o 40 B 7 samples */
		*(.text..fast.sched_clock)	/* kernel/time/sched_clock.o 126 B 21 samples */
		*(.text..fast.dl_server_update)	/* kernel/sched/build_policy.o 42 B 7 samples */
		*(.text..fast.mmiowb_spin_lock)	/* kernel/locking/spinlock.o 36 B 6 samples */
		*(.text..fast.__riscv_sys_clock_gettime)	/* kernel/time/posix-timers.o 30 B 5 samples */
		*(.text..fast.unmask_irq)	/* kernel/irq/chip.o 40 B 6 samples */
		*(.text..fast.add_interrupt_randomness)	/* drivers/char/random.o 150 B 22 samples */
		*(.text..fast.mask_ack_irq)	/* kernel/irq/chip.o 52 B 7 samples */
		*(.text..fast.tick_check_broadcast_expired)	/* kernel/time/tick-broadcast.o 30 B 4 samples */
		*(.text..fast.__sbi_set_timer_v02)	/* arch/riscv/kernel/sbi.o 30 B 4 samples */
		*(.text..fast.__update_load_avg_cfs_rq)	/* kernel/sched/build_policy.o 424 B 55 samples */
		*(.text..fast._copy_to_user)	/* lib/usercopy.o 32 B 4 samples */
		*(.text..fast.__update_load_avg_se)	/* kernel/sched/build_policy.o 468 B 58 samples */
		*(.text..fast.rcu_note_context_switch)	/* kernel/rcu/tree.o 110 B 13 samples */
		*(.text..fast.generic_atomic64_add)	/* lib/atomic64.o 104 B 12 samples */
		*(.text..fast.clic_dev_off)	/* drivers/irqchip/irq-esp32s31-clic.o 26 B 3 samples */
		*(.text..fast.folio_try_get)	/* mm/filemap.o 36 B 4 samples */
		*(.text..fast.__lshrdi3)	/* lib/lshrdi3.o 46 B 5 samples */
		*(.text..fast.__fget_light)	/* fs/file.o 66 B 7 samples */
		*(.text..fast.timerqueue_linked_add)	/* lib/timerqueue.o 128 B 13 samples */
		*(.text..fast.handle_level_irq)	/* kernel/irq/chip.o 120 B 12 samples */
		*(.text..fast.__fget_files_rcu)	/* fs/file.o 110 B 11 samples */
		*(.text..fast.__riscv_sys_ppoll)	/* fs/select.o 30 B 3 samples */
		*(.text..fast.tick_program_event)	/* kernel/time/tick-oneshot.o 124 B 12 samples */
		*(.text..fast.fput)	/* fs/file_table.o 44 B 4 samples */
		*(.text..fast.s31_ext_pa)	/* arch/riscv/kernel/esp32s31-ext.o 44 B 4 samples */
		*(.text..fast.tick_check_oneshot_broadcast_this_cpu)	/* kernel/time/tick-broadcast.o 80 B 7 samples */
		*(.text..fast.clockid_to_kclock)	/* kernel/time/posix-timers.o 70 B 6 samples */
		*(.text..fast.fast_mix)	/* drivers/char/random.o 118 B 10 samples */
		*(.text..fast.dl_server_update_idle)	/* kernel/sched/build_policy.o 48 B 4 samples */
		*(.text..fast.handle_irq_event_percpu)	/* kernel/irq/handle.o 48 B 4 samples */
		*(.text..fast.lock_vma_under_rcu)	/* mm/mmap_lock.o 116 B 9 samples */
		*(.text..fast.handle_irq_event)	/* kernel/irq/handle.o 118 B 9 samples */
		*(.text..fast.unix_poll)	/* net/unix/af_unix.o 162 B 12 samples */
		*(.text..fast.div_s64_rem)	/* lib/math/div64.o 82 B 6 samples */
		*(.text..fast.esp32s31_i2c_isr)	/* drivers/i2c/busses/i2c-esp32s31.o 70 B 5 samples */
		*(.text..fast.set_user_sigmask)	/* kernel/signal.o 72 B 5 samples */
		*(.text..fast.esp32s31_clic_irq_mask)	/* drivers/irqchip/irq-esp32s31-clic.o 58 B 4 samples */
		*(.text..fast.decay_load)	/* kernel/sched/build_policy.o 88 B 6 samples */
		*(.text..fast.get_timespec64)	/* kernel/time/time.o 44 B 3 samples */
		*(.text..fast.rcu_nocb_flush_deferred_wakeup)	/* kernel/rcu/tree.o 44 B 3 samples */
		*(.text..fast.riscv_clock_next_event)	/* drivers/clocksource/timer-riscv.o 60 B 4 samples */
		*(.text..fast.rb_next)	/* lib/rbtree.o 46 B 3 samples */
		*(.text..fast.snd_soc_pcm_component_pointer)	/* sound/soc/soc-component.o 50 B 3 samples */
		*(.text..fast.sock_poll)	/* net/socket.o 120 B 7 samples */
		*(.text..fast.update_curr_dl_se)	/* kernel/sched/build_policy.o 462 B 26 samples */
		*(.text..fast.update_rt_rq_load_avg)	/* kernel/sched/build_policy.o 374 B 20 samples */
		*(.text..fast.update_other_load_avgs)	/* kernel/sched/build_policy.o 98 B 5 samples */
		*(.text..fast.fdget_pos)	/* fs/file.o 60 B 3 samples */
		*(.text..fast.vfs_read)	/* fs/read_write.o 274 B 13 samples */
		*(.text..fast.poll_freewait)	/* fs/select.o 110 B 5 samples */
		*(.text..fast.schedule_timeout)	/* kernel/time/sleep_timeout.o 160 B 7 samples */
		*(.text..fast.eventfd_poll)	/* fs/eventfd.o 70 B 3 samples */
		*(.text..fast.update_dl_rq_load_avg)	/* kernel/sched/build_policy.o 374 B 16 samples */
		*(.text..fast.__handle_irq_event_percpu)	/* kernel/irq/handle.o 400 B 17 samples */
		*(.text..fast.do_sys_poll)	/* fs/select.o 862 B 36 samples */
		*(.text..fast.blk_add_timer)	/* block/blk-timeout.o 100 B 4 samples */
		*(.text..fast.virt_to_slab)	/* mm/slub.o 76 B 3 samples */
		*(.text..fast.poll_select_set_timeout)	/* fs/select.o 128 B 5 samples */
		*(.text..fast.ksys_read)	/* fs/read_write.o 108 B 4 samples */
		*(.text..fast.esp32s31_lcd_vblank_tick)	/* drivers/gpu/drm/espressif/esp32s31-lcd.o 108 B 4 samples */
		*(.text..fast.set_next_task_idle)	/* kernel/sched/build_policy.o 190 B 7 samples */
		*(.text..fast.slab_alloc_node.isra.0)	/* mm/slub.o 194 B 7 samples */
		*(.text..fast.mtree_range_walk)	/* lib/maple_tree.o 250 B 9 samples */
		*(.text..fast.snd_soc_pcm_dai_delay)	/* sound/soc/soc-dai.o 118 B 4 samples */
		*(.text..fast.esp32s31_lcd_irq)	/* drivers/gpu/drm/espressif/esp32s31-lcd.o 188 B 6 samples */
		*(.text..fast.mt_find)	/* lib/maple_tree.o 134 B 4 samples */
		*(.text..fast.note_interrupt)	/* kernel/irq/spurious.o 436 B 13 samples */
		*(.text..fast.rb_insert_color)	/* lib/rbtree.o 208 B 6 samples */
		*(.text..fast.esp32s31_ext_switch)	/* arch/riscv/kernel/esp32s31-ext.o 388 B 11 samples */
		*(.text..fast.free_to_pcs.isra.0)	/* mm/slub.o 108 B 3 samples */
		*(.text..fast._find_next_zero_bit)	/* lib/find_bit.o 108 B 3 samples */
		*(.text..fast.rb_erase)	/* lib/rbtree.o 436 B 12 samples */
		*(.text..fast.set_normalized_timespec64)	/* kernel/time/time.o 110 B 3 samples */
		*(.text..fast.slab_free.isra.0)	/* mm/slub.o 112 B 3 samples */
		*(.text..fast.mas_start)	/* lib/maple_tree.o 112 B 3 samples */
		*(.text..fast.workingset_refault)	/* mm/workingset.o 154 B 4 samples */
		*(.text..fast.vma_start_read)	/* mm/mmap_lock.o 116 B 3 samples */
		*(.text..fast.rpm_check_suspend_allowed)	/* drivers/base/power/runtime.o 116 B 3 samples */
		*(.text..fast.__pollwait)	/* fs/select.o 196 B 5 samples */
		*(.text..fast.kfree)	/* mm/slub.o 122 B 3 samples */
		*(.text..fast.get_sigset_argpack.constprop.0)	/* fs/select.o 122 B 3 samples */
		*(.text..fast.run_posix_cpu_timers)	/* kernel/time/posix-cpu-timers.o 248 B 6 samples */
		*(.text..fast.__mod_node_page_state)	/* mm/vmstat.o 126 B 3 samples */
		*(.text..fast.zone_watermark_fast.isra.0)	/* mm/page_alloc.o 130 B 3 samples */
		*(.text..fast.timespec64_add_safe)	/* kernel/time/time.o 132 B 3 samples */
		*(.text..fast.schedule_hrtimeout_range_clock)	/* kernel/time/sleep_timeout.o 142 B 3 samples */
		*(.text..fast.read_pages)	/* mm/readahead.o 144 B 3 samples */
		*(.text..fast.rcu_core)	/* kernel/rcu/tree.o 252 B 5 samples */
		*(.text..fast.vfs_write)	/* fs/read_write.o 306 B 6 samples */
		*(.text..fast.eventfd_write)	/* fs/eventfd.o 268 B 5 samples */
		*(.text..fast.elv_merge)	/* block/elevator.o 162 B 3 samples */
		*(.text..fast.esp32s31_i2c_xfer)	/* drivers/i2c/busses/i2c-esp32s31.o 782 B 14 samples */
		*(.text..fast.swap_put_entries_cluster)	/* mm/swapfile.o 228 B 4 samples */
		*(.text..fast.handle_edge_irq)	/* kernel/irq/chip.o 176 B 3 samples */
		*(.text..fast.___slab_alloc.isra.0)	/* mm/slub.o 480 B 8 samples */
		*(.text..fast.start_dl_timer)	/* kernel/sched/build_policy.o 302 B 5 samples */
		*(.text..fast.select_estimate_accuracy)	/* fs/select.o 248 B 4 samples */
		*(.text..fast.percpu_counter_add_batch)	/* lib/percpu_counter.o 190 B 3 samples */
		*(.text..fast.core_sys_select)	/* fs/select.o 320 B 5 samples */
		*(.text..fast.poll_select_finish)	/* fs/select.o 288 B 4 samples */
		*(.text..fast.next_uptodate_folio)	/* mm/filemap.o 224 B 3 samples */
		*(.text..fast.handle_mm_fault)	/* mm/memory.o 1512 B 20 samples */
		*(.text..fast.drm_handle_vblank)	/* drivers/gpu/drm/drm_vblank.o 546 B 7 samples */
		*(.text..fast.sized_strscpy)	/* lib/string.o 234 B 3 samples */
		*(.text..fast.do_select)	/* fs/select.o 944 B 12 samples */
		*(.text..fast.__rb_insert_augmented)	/* lib/rbtree.o 236 B 3 samples */
		*(.text..fast.__swap_cache_prepare_and_add.isra.0)	/* mm/swap_state.o 260 B 3 samples */
		*(.text..fast.folio_wait_bit_common)	/* mm/filemap.o 348 B 4 samples */
		*(.text..fast.snd_pcm_update_hw_ptr0)	/* sound/core/pcm_lib.o 562 B 6 samples */
		*(.text..fast.shrink_slab)	/* mm/shrinker.o 412 B 4 samples */
		*(.text..fast.__filemap_add_folio)	/* mm/filemap.o 590 B 5 samples */
		*(.text..fast.blk_map_iter_next)	/* block/blk-mq-dma.o 366 B 3 samples */
		*(.text..fast.get_cycles64)	/* drivers/clocksource/timer-riscv.o 18 B 28 samples */
		*(.text..fast.__alloc_pages_noprof)	/* mm/page_alloc.o 18 B 23 samples */
		*(.text..fast.folio_add_lru)	/* mm/swap.o 32 B 18 samples */
		*(.text..fast.down_read)	/* kernel/locking/rwsem.o 34 B 15 samples */
		*(.text..fast.posix_get_monotonic_timespec)	/* kernel/time/posix-timers.o 16 B 7 samples */
		*(.text..fast.end_swap_bio_read)	/* mm/page_io.o 24 B 10 samples */
		*(.text..fast.irq_can_handle_actions)	/* kernel/irq/chip.o 42 B 16 samples */
		*(.text..fast.kmem_cache_alloc_noprof)	/* mm/slub.o 16 B 6 samples */
		*(.text..fast.mod_node_page_state)	/* mm/vmstat.o 22 B 7 samples */
		*(.text..fast.find_vma)	/* mm/mmap.o 36 B 11 samples */
		*(.text..fast.walk_page_range)	/* mm/pagewalk.o 20 B 6 samples */
		*(.text..fast.mempool_free)	/* mm/mempool.o 34 B 10 samples */
		*(.text..fast.mas_state_walk)	/* lib/maple_tree.o 42 B 11 samples */
		*(.text..fast.__folio_alloc_noprof)	/* mm/page_alloc.o 20 B 5 samples */
		*(.text..fast.mas_walk)	/* lib/maple_tree.o 76 B 18 samples */
		*(.text..fast.update_mmu_cache_range.isra.0)	/* mm/memory.o 38 B 9 samples */
		*(.text..fast.lock_addr)	/* lib/atomic64.o 30 B 7 samples */
		*(.text..fast.percpu_counter_add)	/* mm/memory.o 20 B 4 samples */
		*(.text..fast.__pm_runtime_resume)	/* drivers/base/power/runtime.o 66 B 13 samples */
		*(.text..fast.slab_want_init_on_alloc)	/* mm/slub.o 36 B 7 samples */
		*(.text..fast.mmc_queue_map_sg)	/* drivers/mmc/core/queue.o 26 B 5 samples */
		*(.text..fast.___free_pages)	/* mm/page_alloc.o 68 B 12 samples */
		*(.text..fast.down_read_trylock)	/* kernel/locking/rwsem.o 62 B 10 samples */
		*(.text..fast.__pm_runtime_suspend)	/* drivers/base/power/runtime.o 82 B 13 samples */
		*(.text..fast.account_freepages)	/* mm/page_alloc.o 64 B 10 samples */
		*(.text..fast.folio_put_swap)	/* mm/swapfile.o 66 B 10 samples */
		*(.text..fast.__folio_mod_stat.constprop.0)	/* mm/rmap.o 34 B 5 samples */
		*(.text..fast.mempool_alloc_noprof)	/* mm/mempool.o 72 B 10 samples */
		*(.text..fast.sbitmap_get)	/* lib/sbitmap.o 94 B 13 samples */
		*(.text..fast.arch_dma_cache_inv)	/* arch/riscv/mm/dma-noncoherent.o 58 B 8 samples */
		*(.text..fast.rmap_walk)	/* mm/rmap.o 30 B 4 samples */
		*(.text..fast.rwsem_read_trylock)	/* kernel/locking/rwsem.o 68 B 9 samples */
		*(.text..fast.swap_folio_sector)	/* mm/swapfile.o 70 B 9 samples */
		*(.text..fast.pte_offset_map_lock)	/* mm/pgtable-generic.o 118 B 15 samples */
		*(.text..fast.pte_offset_map_rw_nolock)	/* mm/pgtable-generic.o 32 B 4 samples */
		*(.text..fast.__folio_batch_add_and_move)	/* mm/swap.o 132 B 16 samples */
		*(.text..fast.mmc_issue_type)	/* drivers/mmc/core/queue.o 94 B 11 samples */
		*(.text..fast.esp32s31_clic_irq_ack)	/* drivers/irqchip/irq-esp32s31-clic.o 60 B 7 samples */
		*(.text..fast.prep_new_page)	/* mm/page_alloc.o 52 B 6 samples */
		*(.text..fast.swap_cache_get_folio)	/* mm/swap_state.o 82 B 9 samples */
		*(.text..fast.__blk_rq_map_sg)	/* block/blk-mq-dma.o 188 B 20 samples */
		*(.text..fast.__end_swap_bio_read)	/* mm/page_io.o 108 B 11 samples */
		*(.text..fast.blk_mq_put_tag)	/* block/blk-mq-tag.o 40 B 4 samples */
		*(.text..fast.rcu_all_qs)	/* kernel/rcu/tree.o 142 B 14 samples */
		*(.text..fast.do_swap_page)	/* mm/memory.o 1418 B 137 samples */
		*(.text..fast.folio_mark_dirty)	/* mm/page-writeback.o 52 B 5 samples */
		*(.text..fast.cpu_startup_entry)	/* kernel/sched/build_policy.o 44 B 4 samples */
		*(.text..fast.mtree_load)	/* lib/maple_tree.o 200 B 18 samples */
		*(.text..fast.__blk_mq_get_tag)	/* block/blk-mq-tag.o 134 B 12 samples */
		*(.text..fast.__del_page_from_free_list)	/* mm/page_alloc.o 90 B 8 samples */
		*(.text..fast.blk_rq_map_iter_init)	/* block/blk-mq-dma.o 126 B 11 samples */
		*(.text..fast.free_to_partial_list.isra.0)	/* mm/slub.o 172 B 15 samples */
		*(.text..fast.folio_add_new_anon_rmap)	/* mm/rmap.o 138 B 12 samples */
		*(.text..fast.__get_pfnblock_flags_mask.isra.0)	/* mm/page_alloc.o 60 B 5 samples */
		*(.text..fast.process_mm_walk_lock)	/* mm/pagewalk.o 38 B 3 samples */
		*(.text..fast.__swap_cache_add_folio)	/* mm/swap_state.o 150 B 11 samples */
		*(.text..fast.__free_frozen_pages)	/* mm/page_alloc.o 492 B 36 samples */
		*(.text..fast.folio_add_lru_vma)	/* mm/swap.o 96 B 7 samples */
		*(.text..fast.get_page_from_freelist)	/* mm/page_alloc.o 1306 B 95 samples */
		*(.text..fast.folio_clear_dirty_for_io)	/* mm/page-writeback.o 166 B 12 samples */
		*(.text..fast.swp_tb_to_folio)	/* mm/swap_state.o 56 B 4 samples */
		*(.text..fast.__srcu_read_lock)	/* kernel/rcu/srcutree.o 56 B 4 samples */
		*(.text..fast.swap_cache_alloc_folio)	/* mm/swap_state.o 114 B 8 samples */
		*(.text..fast.pm_runtime_autosuspend_expiration)	/* drivers/base/power/runtime.o 88 B 6 samples */
		*(.text..fast.slab_post_alloc_hook.isra.0)	/* mm/slub.o 44 B 3 samples */
		*(.text..fast.ma_slots)	/* lib/maple_tree.o 44 B 3 samples */
		*(.text..fast.swap_entry_swapped)	/* mm/swapfile.o 60 B 4 samples */
		*(.text..fast.__mod_zone_page_state)	/* mm/vmstat.o 106 B 7 samples */
		*(.text..fast.get_swap_device_info)	/* mm/swapfile.o 94 B 6 samples */
		*(.text..fast.vma_alloc_zeroed_movable_folio.isra.0)	/* mm/memory.o 64 B 4 samples */
		*(.text..fast.folio_free_swap)	/* mm/swapfile.o 98 B 6 samples */
		*(.text..fast.prep_move_freepages_block)	/* mm/page_alloc.o 214 B 13 samples */
		*(.text..fast.workingset_test_recent)	/* mm/workingset.o 122 B 7 samples */
		*(.text..fast.sbitmap_find_bit)	/* lib/sbitmap.o 210 B 12 samples */
		*(.text..fast.get_swap_device)	/* mm/swapfile.o 142 B 8 samples */
		*(.text..fast.__swap_cluster_put_entry)	/* mm/swapfile.o 92 B 5 samples */
		*(.text..fast.__refcount_add_not_zero_limited_acquire.constprop.0)	/* mm/mmap_lock.o 80 B 4 samples */
		*(.text..fast.update_alloc_hint_before_get)	/* lib/sbitmap.o 80 B 4 samples */
		*(.text..fast.free_frozen_page_commit)	/* mm/page_alloc.o 540 B 26 samples */
		*(.text..fast.__rmqueue_pcplist)	/* mm/page_alloc.o 954 B 44 samples */
		*(.text..fast.mempool_free_bulk)	/* mm/mempool.o 176 B 8 samples */
		*(.text..fast.check_new_pages)	/* mm/page_alloc.o 136 B 6 samples */
		*(.text..fast.swap_read_folio)	/* mm/page_io.o 964 B 42 samples */
		*(.text..fast.rmap_walk_anon)	/* mm/rmap.o 240 B 10 samples */
		*(.text..fast.folio_dup_swap)	/* mm/swapfile.o 74 B 3 samples */
		*(.text..fast.sbitmap_queue_clear)	/* lib/sbitmap.o 106 B 4 samples */
		*(.text..fast.free_pages)	/* mm/page_alloc.o 80 B 3 samples */
		*(.text..fast.mlock_vma_folio.isra.0)	/* mm/rmap.o 84 B 3 samples */
		*(.text..fast.rcu_qs)	/* kernel/rcu/tree.o 80 B 43 samples */
		*(.text..fast.mmiowb_set_pending)	/* drivers/irqchip/irq-esp32s31-clic.o 36 B 21 samples */
		*(.text..fast.__raw_spin_unlock)	/* kernel/irq/chip.o 22 B 20 samples */
		*(.text..fast.div_u64_rem)	/* lib/math/div64.o 42 B 17 samples; kernel/sched/build_policy.o 46 B 13 samples */
		*(.text..fast.mmiowb_spin_unlock)	/* kernel/irq/chip.o 48 B 11 samples */
		*(.text..fast.files_lookup_fd_raw)	/* fs/file.o 30 B 10 samples */
		*(.text..fast.irqd_set.isra.0)	/* kernel/irq/chip.o 8 B 8 samples */
		*(.text..fast.esp32s31_intc_clic_irq_eoi)	/* drivers/irqchip/irq-esp32s31-clic.o 2 B 8 samples */
		*(.text..fast.riscv_sched_clock)	/* drivers/clocksource/timer-riscv.o 12 B 27 samples */
		*(.text..fast.raw_notifier_call_chain)	/* kernel/notifier.o 16 B 18 samples */
		*(.text..fast.rcu_segcblist_ready_cbs)	/* kernel/rcu/rcu_segcblist.o 20 B 17 samples */
		*(.text..fast.__accumulate_pelt_segments)	/* kernel/sched/build_policy.o 60 B 38 samples */
		*(.text..fast.account_user_time)	/* kernel/sched/build_policy.o 68 B 42 samples */
		*(.text..fast.topology_scale_freq_tick)	/* drivers/base/arch_topology.o 42 B 20 samples */
		*(.text..fast.ntp_tick_length)	/* kernel/time/ntp.o 22 B 9 samples */
		*(.text..fast.account_group_user_time)	/* kernel/sched/build_policy.o 42 B 17 samples */
		*(.text..fast.rcu_segcblist_is_offloaded)	/* kernel/rcu/tree.o 10 B 4 samples */
		*(.text..fast.task_group_account_field.isra.0)	/* kernel/sched/build_policy.o 52 B 20 samples */
		*(.text..fast.snd_pcm_period_elapsed)	/* sound/core/pcm_lib.o 42 B 15 samples */
		*(.text..fast.esp32s31_clic_irq_unmask)	/* drivers/irqchip/irq-esp32s31-clic.o 58 B 19 samples */
		*(.text..fast.__rb_rotate_set_parents)	/* lib/rbtree.o 34 B 11 samples */
		*(.text..fast._snd_pcm_stream_lock_irqsave)	/* sound/core/pcm_native.o 40 B 12 samples */
		*(.text..fast.kthread_data)	/* kernel/kthread.o 14 B 4 samples */
		*(.text..fast.idr_find)	/* lib/idr.o 16 B 4 samples */
		*(.text..fast.snd_pcm_group_unlock_irq)	/* sound/core/pcm_native.o 30 B 7 samples */
		*(.text..fast.dmaengine_pcm_dma_complete)	/* sound/core/pcm_dmaengine.o 50 B 11 samples */
		*(.text..fast.i2c_adapter_unlock_bus)	/* drivers/i2c/i2c-core-base.o 14 B 3 samples */
		*(.text..fast.i2c_adapter_lock_bus)	/* drivers/i2c/i2c-core-base.o 14 B 3 samples */
		*(.text..fast.snd_pcm_stream_unlock_irqrestore)	/* sound/core/pcm_native.o 38 B 8 samples */
		*(.text..fast.esp32s31_i2c_update)	/* drivers/i2c/busses/i2c-esp32s31.o 42 B 8 samples */
		*(.text..fast.kmem_cache_free)	/* mm/slub.o 32 B 6 samples */
		*(.text..fast.mutex_lock)	/* kernel/locking/mutex.o 32 B 6 samples */
		*(.text..fast.kstat_incr_irqs_this_cpu)	/* kernel/irq/chip.o 22 B 4 samples */
		*(.text..fast.idle_cpu)	/* kernel/sched/build_policy.o 50 B 9 samples */
		*(.text..fast.folio_unlock)	/* mm/filemap.o 28 B 5 samples */
		*(.text..fast.rcu_stall_is_suppressed)	/* kernel/rcu/tree.o 54 B 9 samples */
		*(.text..fast.swap_cluster_lock.isra.0)	/* mm/swapfile.o 24 B 4 samples */
		*(.text..fast.lru_add_drain)	/* mm/swap.o 24 B 4 samples */
		*(.text..fast.s31_ext_check.isra.0)	/* arch/riscv/kernel/esp32s31-ext.o 44 B 7 samples */
		*(.text..fast.account_process_tick)	/* kernel/sched/build_policy.o 120 B 19 samples */
		*(.text..fast.snd_pcm_stream_lock_irq)	/* sound/core/pcm_native.o 38 B 6 samples */
		*(.text..fast.rw_verify_area.constprop.0)	/* fs/read_write.o 26 B 4 samples */
		*(.text..fast.__ashldi3)	/* lib/ashldi3.o 46 B 7 samples */
		*(.text..fast.fifo_pipe_read)	/* fs/pipe.o 46 B 7 samples */
		*(.text..fast.irq_can_handle_pm)	/* kernel/irq/chip.o 150 B 21 samples */
		*(.text..fast.snd_pcm_get_state)	/* sound/core/pcm_native.o 36 B 5 samples */
		*(.text..fast.mutex_unlock)	/* kernel/locking/mutex.o 36 B 5 samples */
		*(.text..fast.snd_pcm_stream_unlock_irq)	/* sound/core/pcm_native.o 22 B 3 samples */
		*(.text..fast.__msecs_to_jiffies)	/* kernel/time/time.o 22 B 3 samples */
		*(.text..fast.__riscv_sys_read)	/* fs/read_write.o 30 B 4 samples */
		*(.text..fast.interleaved_copy)	/* sound/core/pcm_lib.o 62 B 8 samples */
		*(.text..fast.napi_schedule.isra.0)	/* drivers/net/ethernet/espressif/esp32s31-hosted-sram.o 26 B 3 samples */
		*(.text..fast.import_ubuf)	/* lib/iov_iter.o 74 B 8 samples */
		*(.text..fast.kthread_is_per_cpu)	/* kernel/kthread.o 28 B 3 samples */
		*(.text..fast.crc32c)	/* lib/crc/crc32-main.o 38 B 4 samples */
		*(.text..fast.__pte_offset_map)	/* mm/pgtable-generic.o 68 B 7 samples */
		*(.text..fast.rcu_is_cpu_rrupt_from_idle)	/* kernel/rcu/tree.o 68 B 7 samples */
		*(.text..fast.default_write_copy)	/* sound/core/pcm_lib.o 60 B 6 samples */
		*(.text..fast._copy_from_user)	/* lib/usercopy.o 60 B 6 samples */
		*(.text..fast.snd_power_wait)	/* sound/core/init.o 30 B 3 samples */
		*(.text..fast.sg_init_one)	/* lib/scatterlist.o 104 B 10 samples */
		*(.text..fast.snd_soc_pcm_component_delay)	/* sound/soc/soc-component.o 116 B 11 samples */
		*(.text..fast.dmaengine_pcm_pointer)	/* sound/soc/soc-generic-dmaengine-pcm.o 32 B 3 samples */
		*(.text..fast.do_transfer)	/* sound/core/pcm_lib.o 98 B 9 samples */
		*(.text..fast.__dev_pm_qos_resume_latency)	/* drivers/base/power/qos.o 34 B 3 samples */
		*(.text..fast.mlock_drain_local)	/* mm/mlock.o 46 B 4 samples */
		*(.text..fast.blk_rq_timeout)	/* block/blk-timeout.o 36 B 3 samples */
		*(.text..fast.pipe_poll)	/* fs/pipe.o 136 B 10 samples */
		*(.text..fast.account_system_time)	/* kernel/sched/build_policy.o 82 B 6 samples */
		*(.text..fast.post_alloc_hook)	/* mm/page_alloc.o 56 B 4 samples */
		*(.text..fast.mmc_gpio_get_cd)	/* drivers/mmc/core/slot-gpio.o 56 B 4 samples */
		*(.text..fast.switch_mm)	/* arch/riscv/mm/context.o 862 B 58 samples */
		*(.text..fast.snd_pcm_update_state)	/* sound/core/pcm_lib.o 122 B 8 samples */
		*(.text..fast.inotify_poll)	/* fs/notify/inotify/inotify_user.o 78 B 5 samples */
		*(.text..fast.__snd_pcm_lib_xfer)	/* sound/core/pcm_lib.o 1016 B 64 samples */
		*(.text..fast.get_current_ioprio)	/* fs/read_write.o 82 B 5 samples */
		*(.text..fast.i2c_transfer)	/* drivers/i2c/i2c-core-base.o 116 B 7 samples */
		*(.text..fast.kill_fasync)	/* fs/fcntl.o 102 B 6 samples */
		*(.text..fast.pcm_lib_apply_appl_ptr)	/* sound/core/pcm_lib.o 110 B 6 samples */
		*(.text..fast.ntp_get_next_leap)	/* kernel/time/ntp.o 80 B 4 samples */
		*(.text..fast.soc_pcm_pointer)	/* sound/soc/soc-pcm.o 60 B 3 samples */
		*(.text..fast.esp32s31_ppa_isr)	/* drivers/gpu/drm/espressif/esp32s31-ppa.o 60 B 3 samples */
		*(.text..fast.anon_pipe_read)	/* fs/pipe.o 520 B 25 samples */
		*(.text..fast.account_system_index_time)	/* kernel/sched/build_policy.o 84 B 4 samples */
		*(.text..fast.drm_ioctl_kernel)	/* drivers/gpu/drm/drm_ioctl.o 128 B 6 samples */
		*(.text..fast.folio_batch_move_lru)	/* mm/swap.o 168 B 7 samples */
		*(.text..fast.copy_page_to_iter)	/* lib/iov_iter.o 102 B 4 samples */
		*(.text..fast.xas_load)	/* lib/xarray.o 130 B 5 samples */
		*(.text..fast._find_next_bit)	/* lib/find_bit.o 104 B 4 samples */
		*(.text..fast.lru_add)	/* mm/swap.o 222 B 8 samples */
		*(.text..fast.__set_pte_at)	/* arch/riscv/mm/pgtable.o 84 B 3 samples */
		*(.text..fast.__sys_recvfrom)	/* net/socket.o 204 B 7 samples */
		*(.text..fast.lru_add_drain_cpu)	/* mm/swap.o 204 B 7 samples */
		*(.text..fast.xas_start)	/* lib/xarray.o 130 B 4 samples */
		*(.text..fast.gt1158_read)	/* drivers/input/touchscreen/gt1158_polled.o 100 B 3 samples */
		*(.text..fast.set_next_task_rt)	/* kernel/sched/build_policy.o 116 B 3 samples */
