/* 0062 agg-hot (137) + 0069 swap-in fault path (88) + 0073 COLD CONTROL (zero-sample functions, same bytes as the GLQuake list) */
		*(.text..fast.generic_handle_domain_irq)	/* kernel/irq/irqdesc.o 22 B 54 samples */
		*(.text..fast.radix_tree_lookup)	/* lib/radix-tree.o 16 B 30 samples */
		*(.text..fast.handle_irq_desc)	/* kernel/irq/irqdesc.o 46 B 44 samples */
		*(.text..fast.riscv_clocksource_rdtime)	/* drivers/clocksource/timer-riscv.o 12 B 11 samples */
		*(.text..fast.fdget)	/* fs/file.o 14 B 10 samples */
		*(.text..fast.do_raw_spin_lock)	/* kernel/locking/spinlock.o 54 B 38 samples */
		*(.text..fast.__irq_resolve_mapping)	/* kernel/irq/irqdomain.o 76 B 45 samples */
		*(.text..fast.radix_tree_load_root)	/* lib/radix-tree.o 42 B 22 samples */
		*(.text..fast.riscv_intc_irq)	/* drivers/irqchip/irq-riscv-intc.o 76 B 29 samples */
		*(.text..fast.clic_writeb)	/* drivers/irqchip/irq-esp32s31-clic.o 52 B 18 samples */
		*(.text..fast.irq_can_handle)	/* kernel/irq/chip.o 26 B 9 samples */
		*(.text..fast.handle_percpu_devid_irq)	/* kernel/irq/chip.o 220 B 72 samples */
		*(.text..fast.__radix_tree_lookup)	/* lib/radix-tree.o 112 B 31 samples */
		*(.text..fast.esp32s31_clic_handle_irq)	/* drivers/irqchip/irq-esp32s31-clic.o 364 B 94 samples */
		*(.text..fast.put_prev_task_idle)	/* kernel/sched/build_policy.o 24 B 6 samples */
		*(.text..fast.list_lru_count_one)	/* mm/list_lru.o 20 B 5 samples */
		*(.text..fast.drm_crtc_handle_vblank)	/* drivers/gpu/drm/drm_vblank.o 16 B 4 samples */
		*(.text..fast.__kstat_incr_irqs_this_cpu.isra.0)	/* kernel/irq/chip.o 54 B 12 samples */
		*(.text..fast.rb_erase_linked)	/* lib/rbtree.o 56 B 12 samples */
		*(.text..fast.schedule_hrtimeout_range)	/* kernel/time/sleep_timeout.o 14 B 3 samples */
		*(.text..fast.mask_irq)	/* kernel/irq/chip.o 44 B 9 samples */
		*(.text..fast.riscv_timer_interrupt)	/* drivers/clocksource/timer-riscv.o 50 B 10 samples */
		*(.text..fast.put_timespec64)	/* kernel/time/time.o 48 B 9 samples */
		*(.text..fast.riscv_clock_event_stop)	/* drivers/clocksource/timer-riscv.o 40 B 7 samples */
		*(.text..fast.__riscv_isa_extension_available)	/* arch/riscv/kernel/cpufeature.o 40 B 7 samples */
		*(.text..fast.sched_clock)	/* kernel/time/sched_clock.o 126 B 21 samples */
		*(.text..fast.dl_server_update)	/* kernel/sched/build_policy.o 42 B 7 samples */
		*(.text..fast.mmiowb_spin_lock)	/* kernel/locking/spinlock.o 36 B 6 samples */
		*(.text..fast.__riscv_sys_clock_gettime)	/* kernel/time/posix-timers.o 30 B 5 samples */
		*(.text..fast.unmask_irq)	/* kernel/irq/chip.o 40 B 6 samples */
		*(.text..fast.add_interrupt_randomness)	/* drivers/char/random.o 150 B 22 samples */
		*(.text..fast.mask_ack_irq)	/* kernel/irq/chip.o 52 B 7 samples */
		*(.text..fast.tick_check_broadcast_expired)	/* kernel/time/tick-broadcast.o 30 B 4 samples */
		*(.text..fast.__sbi_set_timer_v02)	/* arch/riscv/kernel/sbi.o 30 B 4 samples */
		*(.text..fast.__update_load_avg_cfs_rq)	/* kernel/sched/build_policy.o 424 B 55 samples */
		*(.text..fast._copy_to_user)	/* lib/usercopy.o 32 B 4 samples */
		*(.text..fast.__update_load_avg_se)	/* kernel/sched/build_policy.o 468 B 58 samples */
		*(.text..fast.rcu_note_context_switch)	/* kernel/rcu/tree.o 110 B 13 samples */
		*(.text..fast.generic_atomic64_add)	/* lib/atomic64.o 104 B 12 samples */
		*(.text..fast.clic_dev_off)	/* drivers/irqchip/irq-esp32s31-clic.o 26 B 3 samples */
		*(.text..fast.folio_try_get)	/* mm/filemap.o 36 B 4 samples */
		*(.text..fast.__lshrdi3)	/* lib/lshrdi3.o 46 B 5 samples */
		*(.text..fast.__fget_light)	/* fs/file.o 66 B 7 samples */
		*(.text..fast.timerqueue_linked_add)	/* lib/timerqueue.o 128 B 13 samples */
		*(.text..fast.handle_level_irq)	/* kernel/irq/chip.o 120 B 12 samples */
		*(.text..fast.__fget_files_rcu)	/* fs/file.o 110 B 11 samples */
		*(.text..fast.__riscv_sys_ppoll)	/* fs/select.o 30 B 3 samples */
		*(.text..fast.tick_program_event)	/* kernel/time/tick-oneshot.o 124 B 12 samples */
		*(.text..fast.fput)	/* fs/file_table.o 44 B 4 samples */
		*(.text..fast.s31_ext_pa)	/* arch/riscv/kernel/esp32s31-ext.o 44 B 4 samples */
		*(.text..fast.tick_check_oneshot_broadcast_this_cpu)	/* kernel/time/tick-broadcast.o 80 B 7 samples */
		*(.text..fast.clockid_to_kclock)	/* kernel/time/posix-timers.o 70 B 6 samples */
		*(.text..fast.fast_mix)	/* drivers/char/random.o 118 B 10 samples */
		*(.text..fast.dl_server_update_idle)	/* kernel/sched/build_policy.o 48 B 4 samples */
		*(.text..fast.handle_irq_event_percpu)	/* kernel/irq/handle.o 48 B 4 samples */
		*(.text..fast.lock_vma_under_rcu)	/* mm/mmap_lock.o 116 B 9 samples */
		*(.text..fast.handle_irq_event)	/* kernel/irq/handle.o 118 B 9 samples */
		*(.text..fast.unix_poll)	/* net/unix/af_unix.o 162 B 12 samples */
		*(.text..fast.div_s64_rem)	/* lib/math/div64.o 82 B 6 samples */
		*(.text..fast.esp32s31_i2c_isr)	/* drivers/i2c/busses/i2c-esp32s31.o 70 B 5 samples */
		*(.text..fast.set_user_sigmask)	/* kernel/signal.o 72 B 5 samples */
		*(.text..fast.esp32s31_clic_irq_mask)	/* drivers/irqchip/irq-esp32s31-clic.o 58 B 4 samples */
		*(.text..fast.decay_load)	/* kernel/sched/build_policy.o 88 B 6 samples */
		*(.text..fast.get_timespec64)	/* kernel/time/time.o 44 B 3 samples */
		*(.text..fast.rcu_nocb_flush_deferred_wakeup)	/* kernel/rcu/tree.o 44 B 3 samples */
		*(.text..fast.riscv_clock_next_event)	/* drivers/clocksource/timer-riscv.o 60 B 4 samples */
		*(.text..fast.rb_next)	/* lib/rbtree.o 46 B 3 samples */
		*(.text..fast.snd_soc_pcm_component_pointer)	/* sound/soc/soc-component.o 50 B 3 samples */
		*(.text..fast.sock_poll)	/* net/socket.o 120 B 7 samples */
		*(.text..fast.update_curr_dl_se)	/* kernel/sched/build_policy.o 462 B 26 samples */
		*(.text..fast.update_rt_rq_load_avg)	/* kernel/sched/build_policy.o 374 B 20 samples */
		*(.text..fast.update_other_load_avgs)	/* kernel/sched/build_policy.o 98 B 5 samples */
		*(.text..fast.fdget_pos)	/* fs/file.o 60 B 3 samples */
		*(.text..fast.vfs_read)	/* fs/read_write.o 274 B 13 samples */
		*(.text..fast.poll_freewait)	/* fs/select.o 110 B 5 samples */
		*(.text..fast.schedule_timeout)	/* kernel/time/sleep_timeout.o 160 B 7 samples */
		*(.text..fast.eventfd_poll)	/* fs/eventfd.o 70 B 3 samples */
		*(.text..fast.update_dl_rq_load_avg)	/* kernel/sched/build_policy.o 374 B 16 samples */
		*(.text..fast.__handle_irq_event_percpu)	/* kernel/irq/handle.o 400 B 17 samples */
		*(.text..fast.do_sys_poll)	/* fs/select.o 862 B 36 samples */
		*(.text..fast.blk_add_timer)	/* block/blk-timeout.o 100 B 4 samples */
		*(.text..fast.virt_to_slab)	/* mm/slub.o 76 B 3 samples */
		*(.text..fast.poll_select_set_timeout)	/* fs/select.o 128 B 5 samples */
		*(.text..fast.ksys_read)	/* fs/read_write.o 108 B 4 samples */
		*(.text..fast.esp32s31_lcd_vblank_tick)	/* drivers/gpu/drm/espressif/esp32s31-lcd.o 108 B 4 samples */
		*(.text..fast.set_next_task_idle)	/* kernel/sched/build_policy.o 190 B 7 samples */
		*(.text..fast.slab_alloc_node.isra.0)	/* mm/slub.o 194 B 7 samples */
		*(.text..fast.mtree_range_walk)	/* lib/maple_tree.o 250 B 9 samples */
		*(.text..fast.snd_soc_pcm_dai_delay)	/* sound/soc/soc-dai.o 118 B 4 samples */
		*(.text..fast.esp32s31_lcd_irq)	/* drivers/gpu/drm/espressif/esp32s31-lcd.o 188 B 6 samples */
		*(.text..fast.mt_find)	/* lib/maple_tree.o 134 B 4 samples */
		*(.text..fast.note_interrupt)	/* kernel/irq/spurious.o 436 B 13 samples */
		*(.text..fast.rb_insert_color)	/* lib/rbtree.o 208 B 6 samples */
		*(.text..fast.esp32s31_ext_switch)	/* arch/riscv/kernel/esp32s31-ext.o 388 B 11 samples */
		*(.text..fast.free_to_pcs.isra.0)	/* mm/slub.o 108 B 3 samples */
		*(.text..fast._find_next_zero_bit)	/* lib/find_bit.o 108 B 3 samples */
		*(.text..fast.rb_erase)	/* lib/rbtree.o 436 B 12 samples */
		*(.text..fast.set_normalized_timespec64)	/* kernel/time/time.o 110 B 3 samples */
		*(.text..fast.slab_free.isra.0)	/* mm/slub.o 112 B 3 samples */
		*(.text..fast.mas_start)	/* lib/maple_tree.o 112 B 3 samples */
		*(.text..fast.workingset_refault)	/* mm/workingset.o 154 B 4 samples */
		*(.text..fast.vma_start_read)	/* mm/mmap_lock.o 116 B 3 samples */
		*(.text..fast.rpm_check_suspend_allowed)	/* drivers/base/power/runtime.o 116 B 3 samples */
		*(.text..fast.__pollwait)	/* fs/select.o 196 B 5 samples */
		*(.text..fast.kfree)	/* mm/slub.o 122 B 3 samples */
		*(.text..fast.get_sigset_argpack.constprop.0)	/* fs/select.o 122 B 3 samples */
		*(.text..fast.run_posix_cpu_timers)	/* kernel/time/posix-cpu-timers.o 248 B 6 samples */
		*(.text..fast.__mod_node_page_state)	/* mm/vmstat.o 126 B 3 samples */
		*(.text..fast.zone_watermark_fast.isra.0)	/* mm/page_alloc.o 130 B 3 samples */
		*(.text..fast.timespec64_add_safe)	/* kernel/time/time.o 132 B 3 samples */
		*(.text..fast.schedule_hrtimeout_range_clock)	/* kernel/time/sleep_timeout.o 142 B 3 samples */
		*(.text..fast.read_pages)	/* mm/readahead.o 144 B 3 samples */
		*(.text..fast.rcu_core)	/* kernel/rcu/tree.o 252 B 5 samples */
		*(.text..fast.vfs_write)	/* fs/read_write.o 306 B 6 samples */
		*(.text..fast.eventfd_write)	/* fs/eventfd.o 268 B 5 samples */
		*(.text..fast.elv_merge)	/* block/elevator.o 162 B 3 samples */
		*(.text..fast.esp32s31_i2c_xfer)	/* drivers/i2c/busses/i2c-esp32s31.o 782 B 14 samples */
		*(.text..fast.swap_put_entries_cluster)	/* mm/swapfile.o 228 B 4 samples */
		*(.text..fast.handle_edge_irq)	/* kernel/irq/chip.o 176 B 3 samples */
		*(.text..fast.___slab_alloc.isra.0)	/* mm/slub.o 480 B 8 samples */
		*(.text..fast.start_dl_timer)	/* kernel/sched/build_policy.o 302 B 5 samples */
		*(.text..fast.select_estimate_accuracy)	/* fs/select.o 248 B 4 samples */
		*(.text..fast.percpu_counter_add_batch)	/* lib/percpu_counter.o 190 B 3 samples */
		*(.text..fast.core_sys_select)	/* fs/select.o 320 B 5 samples */
		*(.text..fast.poll_select_finish)	/* fs/select.o 288 B 4 samples */
		*(.text..fast.next_uptodate_folio)	/* mm/filemap.o 224 B 3 samples */
		*(.text..fast.handle_mm_fault)	/* mm/memory.o 1512 B 20 samples */
		*(.text..fast.drm_handle_vblank)	/* drivers/gpu/drm/drm_vblank.o 546 B 7 samples */
		*(.text..fast.sized_strscpy)	/* lib/string.o 234 B 3 samples */
		*(.text..fast.do_select)	/* fs/select.o 944 B 12 samples */
		*(.text..fast.__rb_insert_augmented)	/* lib/rbtree.o 236 B 3 samples */
		*(.text..fast.__swap_cache_prepare_and_add.isra.0)	/* mm/swap_state.o 260 B 3 samples */
		*(.text..fast.folio_wait_bit_common)	/* mm/filemap.o 348 B 4 samples */
		*(.text..fast.snd_pcm_update_hw_ptr0)	/* sound/core/pcm_lib.o 562 B 6 samples */
		*(.text..fast.shrink_slab)	/* mm/shrinker.o 412 B 4 samples */
		*(.text..fast.__filemap_add_folio)	/* mm/filemap.o 590 B 5 samples */
		*(.text..fast.blk_map_iter_next)	/* block/blk-mq-dma.o 366 B 3 samples */
		*(.text..fast.get_cycles64)	/* drivers/clocksource/timer-riscv.o 18 B 28 samples */
		*(.text..fast.__alloc_pages_noprof)	/* mm/page_alloc.o 18 B 23 samples */
		*(.text..fast.folio_add_lru)	/* mm/swap.o 32 B 18 samples */
		*(.text..fast.down_read)	/* kernel/locking/rwsem.o 34 B 15 samples */
		*(.text..fast.posix_get_monotonic_timespec)	/* kernel/time/posix-timers.o 16 B 7 samples */
		*(.text..fast.end_swap_bio_read)	/* mm/page_io.o 24 B 10 samples */
		*(.text..fast.irq_can_handle_actions)	/* kernel/irq/chip.o 42 B 16 samples */
		*(.text..fast.kmem_cache_alloc_noprof)	/* mm/slub.o 16 B 6 samples */
		*(.text..fast.mod_node_page_state)	/* mm/vmstat.o 22 B 7 samples */
		*(.text..fast.find_vma)	/* mm/mmap.o 36 B 11 samples */
		*(.text..fast.walk_page_range)	/* mm/pagewalk.o 20 B 6 samples */
		*(.text..fast.mempool_free)	/* mm/mempool.o 34 B 10 samples */
		*(.text..fast.mas_state_walk)	/* lib/maple_tree.o 42 B 11 samples */
		*(.text..fast.__folio_alloc_noprof)	/* mm/page_alloc.o 20 B 5 samples */
		*(.text..fast.mas_walk)	/* lib/maple_tree.o 76 B 18 samples */
		*(.text..fast.update_mmu_cache_range.isra.0)	/* mm/memory.o 38 B 9 samples */
		*(.text..fast.lock_addr)	/* lib/atomic64.o 30 B 7 samples */
		*(.text..fast.percpu_counter_add)	/* mm/memory.o 20 B 4 samples */
		*(.text..fast.__pm_runtime_resume)	/* drivers/base/power/runtime.o 66 B 13 samples */
		*(.text..fast.slab_want_init_on_alloc)	/* mm/slub.o 36 B 7 samples */
		*(.text..fast.mmc_queue_map_sg)	/* drivers/mmc/core/queue.o 26 B 5 samples */
		*(.text..fast.___free_pages)	/* mm/page_alloc.o 68 B 12 samples */
		*(.text..fast.down_read_trylock)	/* kernel/locking/rwsem.o 62 B 10 samples */
		*(.text..fast.__pm_runtime_suspend)	/* drivers/base/power/runtime.o 82 B 13 samples */
		*(.text..fast.account_freepages)	/* mm/page_alloc.o 64 B 10 samples */
		*(.text..fast.folio_put_swap)	/* mm/swapfile.o 66 B 10 samples */
		*(.text..fast.__folio_mod_stat.constprop.0)	/* mm/rmap.o 34 B 5 samples */
		*(.text..fast.mempool_alloc_noprof)	/* mm/mempool.o 72 B 10 samples */
		*(.text..fast.sbitmap_get)	/* lib/sbitmap.o 94 B 13 samples */
		*(.text..fast.arch_dma_cache_inv)	/* arch/riscv/mm/dma-noncoherent.o 58 B 8 samples */
		*(.text..fast.rmap_walk)	/* mm/rmap.o 30 B 4 samples */
		*(.text..fast.rwsem_read_trylock)	/* kernel/locking/rwsem.o 68 B 9 samples */
		*(.text..fast.swap_folio_sector)	/* mm/swapfile.o 70 B 9 samples */
		*(.text..fast.pte_offset_map_lock)	/* mm/pgtable-generic.o 118 B 15 samples */
		*(.text..fast.pte_offset_map_rw_nolock)	/* mm/pgtable-generic.o 32 B 4 samples */
		*(.text..fast.__folio_batch_add_and_move)	/* mm/swap.o 132 B 16 samples */
		*(.text..fast.mmc_issue_type)	/* drivers/mmc/core/queue.o 94 B 11 samples */
		*(.text..fast.esp32s31_clic_irq_ack)	/* drivers/irqchip/irq-esp32s31-clic.o 60 B 7 samples */
		*(.text..fast.prep_new_page)	/* mm/page_alloc.o 52 B 6 samples */
		*(.text..fast.swap_cache_get_folio)	/* mm/swap_state.o 82 B 9 samples */
		*(.text..fast.__blk_rq_map_sg)	/* block/blk-mq-dma.o 188 B 20 samples */
		*(.text..fast.__end_swap_bio_read)	/* mm/page_io.o 108 B 11 samples */
		*(.text..fast.blk_mq_put_tag)	/* block/blk-mq-tag.o 40 B 4 samples */
		*(.text..fast.rcu_all_qs)	/* kernel/rcu/tree.o 142 B 14 samples */
		*(.text..fast.do_swap_page)	/* mm/memory.o 1418 B 137 samples */
		*(.text..fast.folio_mark_dirty)	/* mm/page-writeback.o 52 B 5 samples */
		*(.text..fast.cpu_startup_entry)	/* kernel/sched/build_policy.o 44 B 4 samples */
		*(.text..fast.mtree_load)	/* lib/maple_tree.o 200 B 18 samples */
		*(.text..fast.__blk_mq_get_tag)	/* block/blk-mq-tag.o 134 B 12 samples */
		*(.text..fast.__del_page_from_free_list)	/* mm/page_alloc.o 90 B 8 samples */
		*(.text..fast.blk_rq_map_iter_init)	/* block/blk-mq-dma.o 126 B 11 samples */
		*(.text..fast.free_to_partial_list.isra.0)	/* mm/slub.o 172 B 15 samples */
		*(.text..fast.folio_add_new_anon_rmap)	/* mm/rmap.o 138 B 12 samples */
		*(.text..fast.__get_pfnblock_flags_mask.isra.0)	/* mm/page_alloc.o 60 B 5 samples */
		*(.text..fast.process_mm_walk_lock)	/* mm/pagewalk.o 38 B 3 samples */
		*(.text..fast.__swap_cache_add_folio)	/* mm/swap_state.o 150 B 11 samples */
		*(.text..fast.__free_frozen_pages)	/* mm/page_alloc.o 492 B 36 samples */
		*(.text..fast.folio_add_lru_vma)	/* mm/swap.o 96 B 7 samples */
		*(.text..fast.get_page_from_freelist)	/* mm/page_alloc.o 1306 B 95 samples */
		*(.text..fast.folio_clear_dirty_for_io)	/* mm/page-writeback.o 166 B 12 samples */
		*(.text..fast.swp_tb_to_folio)	/* mm/swap_state.o 56 B 4 samples */
		*(.text..fast.__srcu_read_lock)	/* kernel/rcu/srcutree.o 56 B 4 samples */
		*(.text..fast.swap_cache_alloc_folio)	/* mm/swap_state.o 114 B 8 samples */
		*(.text..fast.pm_runtime_autosuspend_expiration)	/* drivers/base/power/runtime.o 88 B 6 samples */
		*(.text..fast.slab_post_alloc_hook.isra.0)	/* mm/slub.o 44 B 3 samples */
		*(.text..fast.ma_slots)	/* lib/maple_tree.o 44 B 3 samples */
		*(.text..fast.swap_entry_swapped)	/* mm/swapfile.o 60 B 4 samples */
		*(.text..fast.__mod_zone_page_state)	/* mm/vmstat.o 106 B 7 samples */
		*(.text..fast.get_swap_device_info)	/* mm/swapfile.o 94 B 6 samples */
		*(.text..fast.vma_alloc_zeroed_movable_folio.isra.0)	/* mm/memory.o 64 B 4 samples */
		*(.text..fast.folio_free_swap)	/* mm/swapfile.o 98 B 6 samples */
		*(.text..fast.prep_move_freepages_block)	/* mm/page_alloc.o 214 B 13 samples */
		*(.text..fast.workingset_test_recent)	/* mm/workingset.o 122 B 7 samples */
		*(.text..fast.sbitmap_find_bit)	/* lib/sbitmap.o 210 B 12 samples */
		*(.text..fast.get_swap_device)	/* mm/swapfile.o 142 B 8 samples */
		*(.text..fast.__swap_cluster_put_entry)	/* mm/swapfile.o 92 B 5 samples */
		*(.text..fast.__refcount_add_not_zero_limited_acquire.constprop.0)	/* mm/mmap_lock.o 80 B 4 samples */
		*(.text..fast.update_alloc_hint_before_get)	/* lib/sbitmap.o 80 B 4 samples */
		*(.text..fast.free_frozen_page_commit)	/* mm/page_alloc.o 540 B 26 samples */
		*(.text..fast.__rmqueue_pcplist)	/* mm/page_alloc.o 954 B 44 samples */
		*(.text..fast.mempool_free_bulk)	/* mm/mempool.o 176 B 8 samples */
		*(.text..fast.check_new_pages)	/* mm/page_alloc.o 136 B 6 samples */
		*(.text..fast.swap_read_folio)	/* mm/page_io.o 964 B 42 samples */
		*(.text..fast.rmap_walk_anon)	/* mm/rmap.o 240 B 10 samples */
		*(.text..fast.folio_dup_swap)	/* mm/swapfile.o 74 B 3 samples */
		*(.text..fast.sbitmap_queue_clear)	/* lib/sbitmap.o 106 B 4 samples */
		*(.text..fast.free_pages)	/* mm/page_alloc.o 80 B 3 samples */
		*(.text..fast.mlock_vma_folio.isra.0)	/* mm/rmap.o 84 B 3 samples */
		*(.text..fast.generic_file_readonly_mmap_prepare)	/* mm/filemap.o 32 B 0 samples */
		*(.text..fast.folio_end_read)	/* mm/filemap.o 34 B 0 samples */
		*(.text..fast.filemap_fdatawait_keep_errors)	/* mm/filemap.o 36 B 0 samples */
		*(.text..fast.generic_file_readonly_mmap)	/* mm/filemap.o 38 B 0 samples */
		*(.text..fast.generic_file_mmap)	/* mm/filemap.o 40 B 0 samples */
		*(.text..fast.generic_file_mmap_prepare)	/* mm/filemap.o 42 B 0 samples */
		*(.text..fast.kiocb_invalidate_pages)	/* mm/filemap.o 48 B 0 samples */
		*(.text..fast.filemap_free_folio.isra.0)	/* mm/filemap.o 50 B 0 samples */
		*(.text..fast.filemap_check_errors)	/* mm/filemap.o 54 B 0 samples */
		*(.text..fast.filemap_end_dropbehind)	/* mm/filemap.o 56 B 0 samples */
		*(.text..fast.folio_end_dropbehind)	/* mm/filemap.o 64 B 0 samples */
		*(.text..fast.folio_trylock_flag)	/* mm/filemap.o 64 B 0 samples */
		*(.text..fast.page_cache_next_miss)	/* mm/filemap.o 64 B 0 samples */
		*(.text..fast.filemap_invalidate_pages)	/* mm/filemap.o 70 B 0 samples */
		*(.text..fast.filemap_read_folio)	/* mm/filemap.o 74 B 0 samples */
		*(.text..fast.kiocb_invalidate_post_direct_write)	/* mm/filemap.o 76 B 0 samples */
		*(.text..fast.file_check_and_advance_wb_err)	/* mm/filemap.o 84 B 0 samples */
		*(.text..fast.maybe_unlock_mmap_for_io)	/* mm/filemap.o 84 B 0 samples */
		*(.text..fast.filemap_write_and_wait_range)	/* mm/filemap.o 84 B 0 samples */
		*(.text..fast.filemap_release_folio)	/* mm/filemap.o 90 B 0 samples */
		*(.text..fast.file_write_and_wait_range)	/* mm/filemap.o 92 B 0 samples */
		*(.text..fast.kiocb_write_and_wait)	/* mm/filemap.o 92 B 0 samples */
		*(.text..fast.filemap_get_entry)	/* mm/filemap.o 94 B 0 samples */
		*(.text..fast.filemap_range_has_page)	/* mm/filemap.o 102 B 0 samples */
		*(.text..fast.filemap_writeback)	/* mm/filemap.o 110 B 0 samples */
		*(.text..fast.release_fault_lock)	/* mm/filemap.o 110 B 0 samples */
		*(.text..fast.find_get_entry)	/* mm/filemap.o 114 B 0 samples */
		*(.text..fast.filemap_remove_folio)	/* mm/filemap.o 114 B 0 samples */
		*(.text..fast.filemap_get_folios_tag)	/* mm/filemap.o 116 B 0 samples */
		*(.text..fast.__generic_file_write_iter)	/* mm/filemap.o 116 B 0 samples */
		*(.text..fast.__folio_lock_or_retry)	/* mm/filemap.o 118 B 0 samples */
		*(.text..fast.__filemap_fdatawait_range)	/* mm/filemap.o 120 B 0 samples */
		*(.text..fast.filemap_range_has_writeback)	/* mm/filemap.o 136 B 0 samples */
		*(.text..fast.dio_warn_stale_pagecache)	/* mm/filemap.o 144 B 0 samples */
		*(.text..fast.wake_page_function)	/* mm/filemap.o 146 B 0 samples */
		*(.text..fast.find_get_entries)	/* mm/filemap.o 150 B 0 samples */
		*(.text..fast.__filemap_remove_folio)	/* mm/filemap.o 176 B 0 samples */
		*(.text..fast.splice_folio_into_pipe)	/* mm/filemap.o 186 B 0 samples */
		*(.text..fast.generic_file_direct_write)	/* mm/filemap.o 206 B 0 samples */
		*(.text..fast.generic_file_write_iter)	/* mm/filemap.o 208 B 0 samples */
		*(.text..fast.find_lock_entries)	/* mm/filemap.o 214 B 0 samples */
		*(.text..fast.do_read_cache_folio)	/* mm/filemap.o 240 B 0 samples */
		*(.text..fast.filemap_page_mkwrite)	/* mm/filemap.o 264 B 0 samples */
		*(.text..fast.softleaf_entry_wait_on_locked)	/* mm/filemap.o 292 B 0 samples */
		*(.text..fast.delete_from_page_cache_batch)	/* mm/filemap.o 314 B 0 samples */
		*(.text..fast.filemap_unaccount_folio)	/* mm/filemap.o 324 B 0 samples */
		*(.text..fast.mapping_seek_hole_data)	/* mm/filemap.o 506 B 0 samples */
		*(.text..fast.filemap_splice_read)	/* mm/filemap.o 586 B 0 samples */
		*(.text..fast.___se_sys_cachestat)	/* mm/filemap.o 598 B 0 samples */
		*(.text..fast.cpu_in_idle)	/* kernel/sched/build_policy.o 32 B 0 samples */
		*(.text..fast.update_curr_rt)	/* kernel/sched/build_policy.o 32 B 0 samples */
		*(.text..fast.dl_bw_of)	/* kernel/sched/build_policy.o 34 B 0 samples */
		*(.text..fast.__add_rq_bw)	/* kernel/sched/build_policy.o 34 B 0 samples */
		*(.text..fast.can_nice)	/* kernel/sched/build_policy.o 34 B 0 samples */
		*(.text..fast.___se_sys_sched_rr_get_interval)	/* kernel/sched/build_policy.o 38 B 0 samples */
		*(.text..fast.print_dl_stats)	/* kernel/sched/build_policy.o 40 B 0 samples */
		*(.text..fast.get_prio_dl)	/* kernel/sched/build_policy.o 40 B 0 samples */
		*(.text..fast.dl_task_is_earliest_deadline)	/* kernel/sched/build_policy.o 42 B 0 samples */
		*(.text..fast.___se_sys_sched_get_priority_min)	/* kernel/sched/build_policy.o 42 B 0 samples */
		*(.text..fast.__dl_sub)	/* kernel/sched/build_policy.o 42 B 0 samples */
		*(.text..fast.print_rt_stats)	/* kernel/sched/build_policy.o 44 B 0 samples */
		*(.text..fast.___se_sys_sched_get_priority_max)	/* kernel/sched/build_policy.o 44 B 0 samples */
		*(.text..fast.__dl_add)	/* kernel/sched/build_policy.o 46 B 0 samples */
		*(.text..fast.___se_sys_sched_getscheduler)	/* kernel/sched/build_policy.o 46 B 0 samples */
		*(.text..fast.rq_offline_rt)	/* kernel/sched/build_policy.o 48 B 0 samples */
		*(.text..fast.rt_clear_overload.part.0)	/* kernel/sched/build_policy.o 48 B 0 samples */
		*(.text..fast.rq_offline_dl)	/* kernel/sched/build_policy.o 48 B 0 samples */
		*(.text..fast.dl_clear_overload.part.0)	/* kernel/sched/build_policy.o 48 B 0 samples */
		*(.text..fast.rt_set_overload.part.0)	/* kernel/sched/build_policy.o 50 B 0 samples */
		*(.text..fast.yield_task_dl)	/* kernel/sched/build_policy.o 50 B 0 samples */
		*(.text..fast.dl_set_overload.part.0)	/* kernel/sched/build_policy.o 50 B 0 samples */
		*(.text..fast.sched_set_normal)	/* kernel/sched/build_policy.o 50 B 0 samples */
		*(.text..fast.rq_online_rt)	/* kernel/sched/build_policy.o 50 B 0 samples */
