# Generates buildroot-external/board/esp32-s31/overlay/etc/lvdesk/menu.conf
out = []
def A(s): out.extend(s.split("\n"))
def ind(n): return "  " * n

HEAVY = " (heavy)"
def khz(r): return {11025: "11 kHz", 22050: "22 kHz", 44100: "44 kHz", 48000: "48 kHz"}[r]

A("""# lvdesk application menu - right-click the desktop.
# Two spaces per level. "label = command" runs the command in the terminal;
# a line without "=" is a submenu. Commands run in a login shell of their own
# (profile environment, no terminal); output goes to /tmp/lvdesk-apps.log.
# "@name cmd" runs cmd only if no process called name is already running,
# and raises its window instead. "!console" drops the built-in terminal down
# as the Super+` console ("!terminal" still opens it as a window, but st is
# the menu's terminal now).
#
# LIMITS (lvdesk.c appmenu_load): MENU_MAX 512 non-comment lines (submenus
# count), labels 39 chars (about 33 show), commands 199 chars, lines under
# 300 chars. lvdesk logs "lvdesk: menu: ..." for anything past a limit.
#
# Launch variants (owner request 2026-09-27): each app's OWN switches only -
# every size x fullscreen/window x sound rate where the app takes one. Per
# app: its tuned, known-good line first, then Fullscreen > size > rate and
# Window > size > rate (tuned rate first in each), then extras. "(heavy)" =
# 640x480/800x480 native rendering or a rate that grows the sound cache: it
# may page or not fit in 15.4 MB. Generated by artifacts/menu/genmenu.py;
# the switch reference and what has NO switch: artifacts/menu/VARIANTS.md.
Games
  Doom
    # prboom 2.5.0: -width/-height, -fullscreen/-window. No rate switch
    # (snd_samplerate is config-only, and 2.5.0 ignored it - current-state).
    prboom""")
pb = "@prboom cd /root/doom/wads && /root/doom/prboom"
A(f"      Tuned: 320x240 full = {pb} -width 320 -height 240 -fullscreen")
for mode, sw, word in [("Fullscreen", "-fullscreen", "full"), ("Window", "-window", "window")]:
    A(f"      {mode}")
    for w, h in [(320, 240), (320, 200), (640, 480), (800, 480)]:
        hv = HEAVY if w >= 640 else ""
        A(f"        {w}x{h} {word}{hv} = {pb} -width {w} -height {h} {sw}")
A(f"      320x240 full, no sound = {pb} -width 320 -height 240 -fullscreen -nosound")
A(f"      Timedemo 320x200 full = {pb} -width 320 -height 200 -fullscreen -timedemo demo1")
A("""    Chocolate Doom (SDL2)
      # chocolate-doom 3.1.1: -width/-height (or -geometry) IMPLY a window;
      # the fullscreen size is config-only (fullscreen_width/height), so the
      # one fullscreen line keeps its existing -extraconfig profile (320x240,
      # snd_samplerate 48000). No rate switch: the rate is config-only too.""")
cd = "@chocolate-doom cd /root/doom && ./chocolate-doom"
A(f"      Tuned: 320x240 full, 48 kHz = {cd} -fullscreen -extraconfig /etc/lvdesk/chocolate-fullscreen.cfg")
A("      Window")
for w, h in [(320, 240), (320, 200), (640, 480), (800, 480)]:
    hv = HEAVY if w >= 640 else ""
    A(f"        {w}x{h} window{hv} = {cd} -width {w} -height {h}")
A(f"      320x200 window, no sound = {cd} -window -width 320 -height 200 -1 -nosound -nomusic")
A("""  OpenTyrian
    # Its only switches are --no-sound/--no-joystick/--no-xmas/--data/--net;
    # resolution, fullscreen and scaler are in its own Setup menu.
    Play (sound) = @opentyrian cd /root/oty/usr/share/opentyrian/data && HOME=/root /root/oty/usr/bin/opentyrian --no-joystick
    Play (no sound) = @opentyrian cd /root/oty/usr/share/opentyrian/data && HOME=/root /root/oty/usr/bin/opentyrian --no-sound --no-joystick
  Quake
    # sdlquake 1.0.9 - id's own WinQuake source in Sam Lantinga's SDL 1.2
    # port (rootfs/build-sdlquake.sh), the Quake since 2026-09-25. It asks for
    # 11,025 Hz itself (snd_dma.c desired_speed) - the rate Quake's sounds are
    # recorded at, so nothing is forced - and its fixed 8 MB heap fits where
    # TyrQuake 0.71's 48 kHz sound cache needed 20 MB and swap. Mouse through
    # SDL 1.2 (warp-to-centre, xrel), keys as prboom. Its default is 640x400,
    # so -winsize picks the size (its own option), -fullscreen the mode; it
    # has NO rate switch (desired_speed is a constant). The map-start crash of
    # 09-21 is fixed by -fno-merge-constants in the build (see the script).
    sdlquake (11 kHz fixed)""")
sq = "@sdlquake cd /root/quake && ./sdlquake -basedir /root/quake"
A(f"      Tuned: 320x240 full = {sq} -winsize 320 240 -fullscreen")
for mode, sw, word in [("Fullscreen", " -fullscreen", "full"), ("Window", "", "window")]:
    A(f"      {mode}")
    for w, h in [(320, 240), (640, 480), (800, 480)]:
        hv = HEAVY if w >= 640 else ""
        A(f"        {w}x{h} {word}{hv} = {sq} -winsize {w} {h}{sw}")
A(f"      320x240 full, no sound = {sq} -winsize 320 240 -fullscreen -nosound")
A(f"      Timedemo demo1 = {sq} -winsize 320 240 -fullscreen +timedemo demo1")

def quake_rates(base, rates, rate_sw, default_rate, heavy_rates, panel_ok, tuned_label, td_line, nosound_line):
    """rates: tuned first. rate_sw(r) -> switch text ('' for the app default)."""
    A(f"      Tuned: {tuned_label} = {base} {rate_sw(rates[0])}-width 320 -height 240 -fullscreen")
    for mode, sw, word in [("Fullscreen", "-fullscreen", "full"), ("Window", "-window", "window")]:
        A(f"      {mode}")
        for w, h in [(320, 240), (640, 480), (800, 480)]:
            panel = panel_ok and mode == "Fullscreen" and w == 800
            sheavy = w >= 640 and not panel
            A(f"        {w}x{h}" + (" (panel)" if panel else HEAVY if sheavy else ""))
            for r in rates:
                hv = HEAVY if (sheavy or r in heavy_rates) else ""
                dflt = ""  # labels would pass 33 chars; the default is the first row
                A(f"          {w}x{h} {word}, {khz(r)}{dflt}{hv} = {base} {rate_sw(r)}-width {w} -height {h} {sw}")
    A(f"      {nosound_line}")
    A(f"      {td_line}")

A("""    TyrQuake 0.71 (X11 software)
      # Stock TyrQuake 0.71, X11 video, SDL2 sound. Its own default rate is
      # 48 kHz (snd_sdl.c SND_DEFAULT_RATE) and -mem 20 is the known-good
      # line for it; -sndspeed picks another rate. Sounds are resampled to
      # that rate when cached, so a lower rate is lighter, not heavier.""")
tx = "@tyr-quake-x11 cd /root/quake && HOME=/root/quake ./tyr-quake-x11 -basedir /root/quake -mem 20"
quake_rates(tx, [48000, 11025, 22050, 44100], lambda r: "" if r == 48000 else f"-sndspeed {r} ",
            48000, (), False, "320x240 full, 48 kHz",
            f"Timedemo demo1, 48 kHz = {tx} -width 320 -height 240 -fullscreen +timedemo demo1",
            f"320x240 full, no sound = {tx} -nosound -width 320 -height 240 -fullscreen")
A("""    GLQuake (QuakeSpasm, SDL 1.2 GL)
      # Stock QuakeSpasm 0.96.3 (rootfs/build-quakespasm.sh) through SDL 1.2
      # GLX and our libGL, from SD like the other Quakes. Its own switches
      # only: -mixspeed is its OUTPUT rate (default 44100; -sndspeed, the sfx
      # cache rate, already defaults to 11025, Quake's recorded rate), so
      # -mixspeed 11025 runs the mixer and ALSA at 11 kHz with no lowpass -
      # nothing forced by the platform; 22/44/48 kHz cost mixer CPU, not
      # memory. -zone 384 is its own old 32-bit zone size (the 4 MB
      # default is memset at start and holds only strings here);
      # -heapsize 12288 is the smallest hunk that plays demo1 without the
      # Cache thrashing (10.5 MB loads but reloads models and skins every
      # few frames; 10 MB and 8 MB fail at map load). The shareware pak
      # ignores "+commands" (QuakeSpasm stuffs the command line only for
      # the registered game), so the timedemo runs from /root/quake/td,
      # whose id1/autoexec.cfg says "timedemo demo1" (scripts/board/
      # glquake-setup.sh); the result stays on the console at the end and
      # -condebug also writes it to /root/quake/td/qconsole.log. 800x480
      # fullscreen is panel size, where the desktop's GL render scale
      # applies; 640x480 and the windows render natively. Numbers:
      # artifacts/gl/glquake/README.md.""")
qs = "@quakespasm cd /root/quake && ./quakespasm -basedir /root/quake -heapsize 12288 -zone 384"
quake_rates(qs, [11025, 22050, 44100, 48000], lambda r: f"-mixspeed {r} ", None, (), True,
            "320x240 full, 11 kHz",
            "Timedemo demo1 (full, 11 kHz) = @quakespasm cd /root/quake/td && /root/quake/quakespasm -basedir /root/quake/td -condebug -mixspeed 11025 -heapsize 12288 -zone 384 -width 320 -height 240 -fullscreen",
            f"320x240 full, no sound = {qs} -nosound -width 320 -height 240 -fullscreen")
A("""    GLQuake (TyrQuake 0.71, X11 GLX)
      # Stock TyrQuake 0.71 GL (rootfs/build-tyrglquake-x11.sh), X11 video
      # through xlite and GLX through our libGL, SDL2 sound only; from SD in
      # /root/tyrgl with its own basedir and HOME (config and qconsole.log in
      # /root/tyrgl/.tyrquake/id1, apart from QuakeSpasm's). Its own switches
      # only: -sndspeed 11025 (Quake's recorded rate; its default is 48 kHz),
      # -heapsize 14336 (the smallest that does not reload models from the
      # pak every few frames - 13312 did), 320x240. -sndspeed is also the
      # rate the sounds are CACHED at in that heap, so 44/48 kHz hold about
      # 4x the sound data and may thrash it (heavy). TyrQuake stuffs
      # "+commands" itself, so the timedemo needs no autoexec. Its gamma
      # (Options > Brightness) is a VidMode gamma ramp, fullscreen only.
      # Numbers: artifacts/gl/tyrquake/README.md.""")
tg = "@tyr-glquake cd /root/tyrgl && HOME=/root/tyrgl ./tyr-glquake -basedir /root/tyrgl -heapsize 14336"
quake_rates(tg, [11025, 22050, 44100, 48000], lambda r: f"-sndspeed {r} ", None, (44100, 48000), True,
            "320x240 full, 11 kHz",
            f"Timedemo demo1 (full, 11 kHz) = {tg} -condebug -sndspeed 11025 -width 320 -height 240 -fullscreen +timedemo demo1",
            f"320x240 full, no sound = {tg} -nosound -width 320 -height 240 -fullscreen")
A("""  GL demos
    # Stock mesa-demos 9.0.0, freeglut and SDL's testgl through our libGL
    # (docs/gl-plan-2026-09-25.md), kept like the other apps: binaries in
    # /root/gl2/bin, GLU and freeglut in /root/gl2/lib, data where the demos
    # were built to look (/usr/share/mesa-demos). Arrow keys; Esc quits.
    # None has sound. glxgears: -geometry WxH for a window (default 300x300);
    # -fullscreen is always the panel size (it ignores -geometry). The GLUT
    # demos all call glutInitWindowSize BEFORE glutInit, so freeglut's own
    # -geometry wins; GLUT has no fullscreen switch. manywin needs a window
    # count (no argument only prints its usage); lvdesk shows 4 X windows.
    # testgl: fixed 640x480, -fullscreen its only mode switch.""")
gl = "cd /root/gl2 && LD_LIBRARY_PATH=/root/gl2/lib"
A("    Gears (glxgears)")
A(f"      Tuned: window 300x300 = @glxgears {gl} ./bin/glxgears")
A(f"      Fullscreen (panel) = @glxgears {gl} ./bin/glxgears -fullscreen")
for w, h in [(320, 240), (640, 480), (800, 480)]:
    hv = HEAVY if w >= 640 else ""
    A(f"      {w}x{h} window{hv} = @glxgears {gl} ./bin/glxgears -geometry {w}x{h}")
A("    GLUT demos")
for lab, b, dw, dh in [("Gears (GLUT)", "gears", 300, 300), ("Morph 3D", "morph3d", 640, 480),
                       ("Bounce", "bounce", 600, 450), ("Gear train", "geartrain", 640, 480),
                       ("Isosurface", "isosurf", 400, 400), ("Terrain (fly)", "terrain", 640, 480),
                       ("Tunnel", "tunnel", 640, 480), ("Fire", "fire", 640, 480),
                       ("Teapot", "teapot", 640, 480), ("Textured cylinder", "texcyl", 400, 400),
                       ("Specular texture", "spectex", 300, 300), ("Image perspective", "ipers", 640, 480)]:
    A(f"      {lab}")
    dhv = HEAVY if dw >= 600 else ""
    A(f"        Default {dw}x{dh} window{dhv} = @{b} {gl} ./bin/{b}")
    for w, h in [(320, 240), (640, 480), (800, 480)]:
        if (w, h) == (dw, dh):
            continue
        hv = HEAVY if w >= 640 else ""
        A(f"        {w}x{h} window{hv} = @{b} {gl} ./bin/{b} -geometry {w}x{h}")
A("    Many windows")
for n in (2, 3, 4):
    A(f"      {n} windows = @manywin {gl} ./bin/manywin {n}")
A(f"    Hidden line (polygon offset) = @offset {gl} ./bin/offset")
A("    SDL 1.2 GL test")
A(f"      Window 640x480 = @testgl {gl} ./bin/testgl")
A(f"      Fullscreen = @testgl {gl} ./bin/testgl -fullscreen")
A("""Apps
  Files = @xfiles xfiles /root
  Calculator = @xcalc xcalc
  Clock = @xclock xclock
  Terminal = st
System
  Console (Super+`) = !console
  Shortcuts (Super+/) = !shortcuts""")
import sys
open(sys.argv[1], "w").write("\n".join(out) + "\n")
