#!/bin/bash
# audio48k-p0.sh <label> - step 0 of docs/audio-48k-plan-2026-09-25.md: the
# audio path's share of CPU0 under the X11 TyrQuake timedemo at the 48 kHz it
# asks for (-mem 20, fullscreen). No build. One fresh boot, ~5 min.
#
# Host side: reset.py, then ONE short runsh that launches the board child
# under setsid with its output on the card (/root/ap0/), then bounded runsh
# polls (each sleeps <= 40 s board-side) until the child writes AP0_DONE, then
# one runsh that cats the results back (~80 kB). Nothing slow runs inside a
# runsh window, and no second board tool is ever started while one is open.
#
# Board child, in order (no forks during the sampler window):
#   aplay -v on "default" at 48000/S16_LE/2 from /dev/zero for 1 s: the chain
#     dump (silence; DAC at 110 first) - names the outer plug and whether it
#     inserted any conversion;
#   launch ./tyr-quake-x11 id1 -mem 20 fullscreen +timedemo demo1, with
#     S31ROUTE_DEBUG=1 (our plugin's open-time print of app rate/ring -> sink
#     rate/ring; it changes nothing in the stream);
#   settle $SETTLE s (default 60: past the map load); threads + comm; maps; /proc/asound hw_params, sw_params,
#     status (with uptime, so hw_ptr/s gives the real rate);
#   pin the whole game to CPU0 (pin -p 0), snapshot A (interrupts, every
#     thread's stat and ctxt switches), 2 x 4000 h1s samples = 8 s,
#     50 x 0.2 s samples of the audio thread's wchan / state / majflt /
#     syscall (and /proc/<tid>/stack if the kernel has it), snapshot B
#     (~20 s after A), status again;
#   wait for the demo's RESULT line, DACL/DACR back to 143, kill the game.
set -u
cd "$(dirname "$0")/../.."
L=${1:?usage: audio48k-p0.sh <label>}
CTRL=${H1S_CTRL:-0x2f031968}; BUF=${H1S_BUF:-0x2f026630}
# SETTLE: seconds from launch to the window. At -mem 20 / 48 kHz the map load
# (precache: S_LoadSound -> S_FilterSfx, the game's own sfx filter) ends ~38 s
# after launch; run1 used 15 s and sampled the LOAD (56.6% S_FilterSfx), not play.
SETTLE=${SETTLE:-60}
OUT=artifacts/perf-plan/audio48k-p0-$L-$(date +%H%M%S); mkdir -p "$OUT"
C=$OUT/child.sh
cat > "$C" <<EOF
#!/bin/sh
# generated by scripts/board/audio48k-p0.sh
D=/root/ap0
exec >\$D/log.txt 2>&1
while :; do read u r < /proc/uptime; [ \${u%%.*} -ge 150 ] && break; sleep 5; done
echo "UNAME \$(uname -a)"
echo "UPTIME \$(cat /proc/uptime)"
md5sum /usr/lib/alsa-lib/libasound_module_pcm_s31route.so /usr/lib/libasound.so.2.0.0 /usr/lib/libSDL2-2.0.so.0.3200.10 /root/quake/tyr-quake-x11 2>&1 | sed 's/^/MD5 /'
echo "ASOUND_CONF_BEGIN"; grep -v '^#' /etc/asound.conf | grep .; echo "ASOUND_CONF_END"
echo "CARDS \$(cat /proc/asound/cards | tr -s ' ' | tr '\n' '|')"
echo "PCMS \$(cat /proc/asound/pcm | tr '\n' '|')"
echo "SINK \$(cat /run/s31-sink 2>/dev/null || echo none)"
chmod +x /root/h1s /root/pin 2>/dev/null
for p in \$(ps | awk '/[t]iopex|[t]yr-quake|[t]yrquake/ {print \$1}'); do kill -9 \$p 2>/dev/null; done
amixer -q sset 'DACL' 110 2>/dev/null; amixer -q sset 'DACR' 110 2>/dev/null
echo "APLAY_BEGIN"
S31ROUTE_DEBUG=1 aplay -v -D default -t raw -f S16_LE -c 2 -r 48000 --period-size=2048 --buffer-size=8192 -d 1 /dev/zero 2>&1 | head -80
echo "APLAY_END"
cd /root/quake
rm -f /root/-basedir/qconsole.log /root/quake/id1/qconsole.log /root/quake/.tyrquake/id1/qconsole.log
setsid sh -c 'DISPLAY=:0 HOME=/root/quake S31ROUTE_DEBUG=1 exec ./tyr-quake-x11 id1 -basedir /root/quake -mem 20 -width 320 -height 240 -fullscreen -condebug +timedemo demo1 >/root/quake/td.log 2>&1' </dev/null >/dev/null 2>&1 &
sleep $SETTLE
P=\$(ps | awk '/[t]yr-quake/ {print \$1}' | head -1)
echo "QPID \${P:-NONE} uptime \$(cat /proc/uptime) demo_started=\$(grep -ac Necropolis /root/quake/.tyrquake/id1/qconsole.log 2>/dev/null)"
[ -n "\$P" ] || { echo "NO_QUAKE"; cat /root/quake/td.log; echo AP0_DONE; exit 0; }
A=""
for t in /proc/\$P/task/*; do n=\$(cat \$t/comm); echo "TASK \${t##*/} \$n"; case "\$n" in SDLAudioP*) A=\${t##*/};; esac; done
echo "AUDIO_TID \${A:-NONE}"
cat /proc/\$P/maps > \$D/maps.txt
echo "LOADED_ALSA \$(grep -aoE '[^/ ]*(asound|SDL2|alsa)[^/ ]*\$' \$D/maps.txt | sort -u | tr '\n' ' ')"
S=/proc/asound/card0/pcm0p/sub0
for f in info hw_params sw_params; do echo "== \$f"; cat \$S/\$f; done
echo "== status1 uptime \$(cat /proc/uptime)"; cat \$S/status
for c in /proc/asound/card*/pcm*p/sub*/hw_params; do echo "OPEN? \$c: \$(head -1 \$c)"; done
/root/pin -p 0 \$P
snap() {
	d=\$D/snap\$1; mkdir -p \$d
	cat /proc/uptime > \$d/uptime
	cat /proc/interrupts > \$d/interrupts
	for t in /proc/\$P/task/*; do echo "\${t##*/} \$(cat \$t/stat)"; done > \$d/tstat
	for t in /proc/\$P/task/*; do echo "\${t##*/} \$(grep ctxt \$t/status | tr -s ' \t' ' ' | tr '\n' ' ')"; done > \$d/tctxt
	grep -E '^(pgmajfault|pswpin) ' /proc/vmstat > \$d/vmstat
}
snap A
/root/h1s $CTRL $BUF 4000 > \$D/prof.txt 2>\$D/prof.err
/root/h1s $CTRL $BUF 4000 >> \$D/prof.txt 2>>\$D/prof.err
HAS_STACK=0; [ -r /proc/\$P/task/\$A/stack ] && HAS_STACK=1
echo "PROC_STACK \$HAS_STACK \$(ls -l /proc/\$P/task/\$A/stack 2>&1)"
i=0
while [ \$i -lt 50 ]; do
	read w < /proc/\$P/task/\$A/wchan
	read st < /proc/\$P/task/\$A/stat
	read sc < /proc/\$P/task/\$A/syscall
	set -- \$st
	echo "W \$i \$3 \${12} \$w | \$sc"
	[ \$HAS_STACK = 1 ] && { echo "STACK \$i"; cat /proc/\$P/task/\$A/stack; }
	usleep 200000
	i=\$((i + 1))
done > \$D/wchan.txt
snap B
echo "== status2 uptime \$(cat /proc/uptime)"; cat \$S/status
echo "CAPS \$(grep -c . \$D/prof.txt) err \$(head -c 200 \$D/prof.err | tr '\n' ' ')"
sleep 30
i=0; while [ \$i -lt 60 ]; do grep -aqE "[0-9]+ frames" /root/quake/id1/qconsole.log /root/quake/.tyrquake/id1/qconsole.log 2>/dev/null && break; grep -aq "^Error:" /root/quake/td.log 2>/dev/null && break; sleep 4; i=\$((i+1)); done
echo "RESULT_UPTIME \$(cat /proc/uptime)"
echo "RESULT \$(grep -ahE '[0-9]+ frames' /root/quake/id1/qconsole.log /root/quake/.tyrquake/id1/qconsole.log 2>/dev/null | head -1)"
echo "QUAKE majflt=\$(awk '{print \$12}' /proc/\$P/stat 2>/dev/null) \$(grep -aE 'VmRSS|VmSwap' /proc/\$P/status 2>/dev/null | tr -s ' ' | tr '\n' ' ')"
echo "QCON_AUDIO \$(grep -ahiE 'sound|audio|hz|sdl' /root/quake/.tyrquake/id1/qconsole.log /root/quake/id1/qconsole.log 2>/dev/null | head -12 | tr '\n' '|')"
echo "TDLOG_BEGIN"; head -c 3000 /root/quake/td.log; echo; echo "TDLOG_END"
kill -9 \$P 2>/dev/null
amixer -q sset 'DACL' 143 2>/dev/null; amixer -q sset 'DACR' 143 2>/dev/null
echo "DAC \$(amixer sget DACL 2>/dev/null | grep -o 'Playback [0-9]*' | head -1) / \$(amixer sget DACR 2>/dev/null | grep -o 'Playback [0-9]*' | head -1)"
echo AP0_DONE
EOF
B64=$(base64 < "$C" | tr -d '\n')
cat > "$OUT/launch.sh" <<EOF
rm -rf /root/ap0; mkdir -p /root/ap0
echo '$B64' | base64 -d > /root/ap0/child.sh
setsid sh /root/ap0/child.sh </dev/null >/dev/null 2>&1 &
echo LAUNCHED \$(wc -c < /root/ap0/child.sh)
EOF
cat > "$OUT/poll.sh" <<'EOF'
i=0; while [ $i -lt 8 ]; do grep -q AP0_DONE /root/ap0/log.txt 2>/dev/null && break; sleep 5; i=$((i+1)); done
grep -q AP0_DONE /root/ap0/log.txt 2>/dev/null && echo POLL_DONE || echo "POLL_WAIT $(tail -c 120 /root/ap0/log.txt 2>/dev/null | tr '\n' ' ')"
EOF
cat > "$OUT/collect.sh" <<'EOF'
cd /root/ap0
for f in log.txt maps.txt wchan.txt prof.txt snapA/uptime snapA/interrupts snapA/tstat snapA/tctxt snapA/vmstat snapB/uptime snapB/interrupts snapB/tstat snapB/tctxt snapB/vmstat; do echo "==> $f <=="; cat $f; done
amixer -q sset 'DACL' 143 2>/dev/null; amixer -q sset 'DACR' 143 2>/dev/null
echo COLLECT_END
EOF
echo "audio48k-p0 [$L] -> $OUT"
python3 scripts/board/reset.py > "$OUT/reset.log" 2>&1 || { echo "reset failed"; cat "$OUT/reset.log"; exit 3; }
python3 scripts/board/runsh.py "$OUT/launch.sh" 60 170 2>&1 | tr -d '\r' > "$OUT/launch.log"
grep -q '^LAUNCHED' "$OUT/launch.log" || { echo "launch failed:"; tail -20 "$OUT/launch.log"; exit 3; }
n=0
while [ $n -lt 12 ]; do
	python3 scripts/board/runsh.py "$OUT/poll.sh" 60 0 2>&1 | tr -d '\r' > "$OUT/poll.log"
	grep -q '^POLL_DONE' "$OUT/poll.log" && break
	grep -aE 'SERIAL PORT BUSY|NO_SHELL|RS_TIMEKILL' "$OUT/poll.log" && { echo "poll failed"; exit 3; }
	echo "  poll $n: $(grep -a '^POLL_WAIT' "$OUT/poll.log" | cut -c1-140)"
	n=$((n + 1))
done
python3 scripts/board/runsh.py "$OUT/collect.sh" 90 0 2>&1 | tr -d '\r' > "$OUT/collect.log"
grep -q '^COLLECT_END' "$OUT/collect.log" || echo "WARNING: collect incomplete"
awk -v d="$OUT" '/^==> .* <==$/ { n = $2; gsub("/", "_", n); f = d "/" n; next } /^COLLECT_END/ { f = "" } f { print > f }' "$OUT/collect.log"
echo "audio48k-p0 [$L]: done -> $OUT"
