#!/usr/bin/env python3
"""fastfn-pick.py <System.map> <fn-index> <budget bytes> <out.list> [--cold] <samples.txt>...

Choose the functions to move into RAM text by name (perf-plan 2026-09-23 C39).
Ranks FLASH-text functions ([_stext,_etext)) by hart-1 PC samples per byte,
takes the densest until <budget> bytes are used, and writes
  <obj> <function>          (the S31_FASTFN_LIST format scripts/Makefile.lib reads)
plus arch/riscv/kernel/s31-fastfn.lds.h ordering them hot-first. --cold picks
functions with ZERO samples from the same objects to the same total size: the
layout control every text move needs (memory s31-fasttext-candidates: a cold
18 kB move was -7.1%).

Excluded by name: anything that implements the XIP copy or cache maintenance
(memcpy/memset, arch_sync_dma_*, esp32s31_cache*, setup_vm*, the early boot
path) - code cannot live in what its own mechanism moves. Ambiguous names
(559 static duplicates in the index) are skipped unless the object is unique.
"""
import bisect
import sys
from collections import Counter, defaultdict

args = sys.argv[1:]
cold = "--cold" in args
if cold:
    args.remove("--cold")
if len(args) < 5:
    sys.exit(__doc__)
smap, index, budget, out = args[0], args[1], int(args[2]), args[3]
samples = args[4:]

FORBID_PREFIX = ("memcpy", "memset", "memmove", "arch_sync_dma", "esp32s31_cache",
                 "setup_vm", "_start", "relocate", "__riscv_save", "__riscv_restore",
                 "riscv_fill_hwcap", "sbi_", "clear_bss", "early_", "kernel_init",
                 "esp32s31_flush", "esp32s31_dcache", "esp32s31_icache")
FORBID_OBJ_PREFIX = ("arch/riscv/mm/init.o", "arch/riscv/kernel/head.o",
                     "drivers/cache/", "arch/riscv/lib/", "init/",
                     # assembly has no per-function sections to rename
                     "arch/riscv/kernel/entry.o", "arch/riscv/kernel/fpu.o",
                     "arch/riscv/kernel/mcount.o", "arch/riscv/kernel/sbi_ecall.o")
# __lockfunc (.spinlock.text), __exit and __sched code are not split either
FORBID_NAME_PREFIX = ("_raw_", "ldsem_", "__se_sys_", "__do_sys_")
FORBID_NAME_SUFFIX = ("_exit",)

# <System.map> may be an `nm -nS vmlinux` listing (addr size type name): sizes
# make attribution exact. A plain System.map (no sizes) blames every PC in a
# gap on the nearest preceding name - the dry run charged 106 idle samples to
# input_proc_exit, an __exit function that never runs.
syms, marks = [], {}
for line in open(smap):
    p = line.split()
    if len(p) < 3:
        continue
    a = int(p[0], 16)
    if len(p) == 4:
        size, typ, name = int(p[1], 16), p[2], p[3]
    else:
        size, typ, name = None, p[1], p[2]
    if name in ("_stext", "_etext"):
        marks[name] = a
    if typ in "tTwW":
        syms.append((a, name, size))
syms.sort()
addrs = [a for a, _, _ in syms]
lo, hi = marks["_stext"], marks["_etext"]

objs = defaultdict(list)   # name -> [(obj, size)]
for line in open(index):
    p = line.split()
    if len(p) == 3:
        objs[p[0]].append((p[1], int(p[2], 16)))

hits = Counter()
total = 0
for sp in samples:
    for line in open(sp):
        line = line.strip()
        try:
            pc = int(line, 16)
        except ValueError:
            continue
        total += 1
        if lo <= pc < hi:
            i = bisect.bisect_right(addrs, pc) - 1
            a, name, size = syms[i]
            if size is None or pc < a + size:
                hits[name] += 1
            else:
                hits["<unattributed>"] += 1

def allowed(name, obj):
    if name.startswith(FORBID_PREFIX) or name.startswith(FORBID_NAME_PREFIX) or name.endswith(FORBID_NAME_SUFFIX):
        return False
    if obj.startswith(FORBID_OBJ_PREFIX):
        return False
    return True

cands = []
flash_names = {name for a, name, _ in syms if lo <= a < hi}
for name in flash_names:
    o = objs.get(name)
    if not o or len(o) != 1:
        continue
    obj, size = o[0]
    if size == 0 or not allowed(name, obj):
        continue
    cands.append((hits[name] / size, hits[name], size, obj, name))

if cold:
    pool = [c for c in cands if c[1] == 0]
    hot = sorted([c for c in cands if c[1] > 0], reverse=True)
    hot_objs = Counter()
    for c in hot:
        hot_objs[c[3]] += 1
    pool.sort(key=lambda c: (-hot_objs[c[3]], c[2]))
    pick = pool
else:
    pick = sorted([c for c in cands if c[1] >= 3], reverse=True)

chosen, used, hit_sum = [], 0, 0
for dens, h, size, obj, name in pick:
    if used + size > budget:
        continue
    chosen.append((obj, name, size, h))
    used += size
    hit_sum += h
    if budget - used < 64:
        break

with open(out, "w") as f:
    for obj, name, size, h in chosen:
        f.write("%s %s\n" % (obj, name))
frag = out.rsplit(".", 1)[0] + ".lds.h"
with open(frag, "w") as f:
    f.write("/* generated by scripts/board/fastfn-pick.py: %d functions, %d bytes, %s */\n" % (
        len(chosen), used, "COLD CONTROL" if cold else "hot-first"))
    for obj, name, size, h in chosen:
        f.write("\t\t*(.text..fast.%s)\t/* %s %d B %d samples */\n" % (name, obj, size, h))
print("unattributed flash samples (gaps, unsized): %d" % hits["<unattributed>"])
print("%s: %d functions, %d bytes, %d of %d samples (%.1f%% of all, %.1f%% of flash text)" % (
    "cold control" if cold else "hot list", len(chosen), used, hit_sum, total,
    100.0 * hit_sum / max(total, 1), 100.0 * hit_sum / max(sum(hits.values()), 1)))
for obj, name, size, h in chosen[:12]:
    print("  %6d B %5d smp  %-32s %s" % (size, h, name, obj))
print("list: %s   fragment: %s" % (out, frag))
