#!/bin/bash
# paging-p1.sh <label> - one FRESH-BOOT window of the paging plan's no-build
# first measurements (docs/paging-plan-2026-09-25.md, items 1, 2, 3, 5).
#
#   SCHED=kyber RING=1 SDLAT=1 scripts/board/paging-p1.sh sched-kyber   # item 5
#   PROCS=1 LVSTAT=1 scripts/board/paging-p1.sh split                     # items 1-3
#   PRE='echo 50 > /proc/sys/vm/watermark_scale_factor' scripts/board/paging-p1.sh wsf50
#
# The load is the X11 TyrQuake -mem 20 timedemo at the 48 kHz it asks for
# (./tyr-quake-x11 id1 -mem 20 -fullscreen +timedemo demo1), the same
# invocation as the 2b/sdtrace -mem 20 series. MODE=attract drops the
# +timedemo so Quake runs its startdemos loop at real-time pace ("play"
# without input injection). Board timeline:
#
#   uptime >= 150 s (the harness's 170 s-from-reset settle, measured on the
#   board) -> optional LVSTAT desktop snapshot -> $PRE -> launch -> SETTLE s
#   -> snapshot A -> WINDOW s of sampling -> snapshot B -> the demo's RESULT.
#
# Inside the window, every STEP s (default 3): RING=1 dumps both halves of
# the 64-entry sdtrace ring to the console (host dedupes by seq); PROCS=1
# every 3rd step (~9-10 s) prints VmRSS/VmSwap for every process. SDLAT=1
# runs rootfs/sdlat pinned to CPU1 as a SAMPLING probe: 4 KiB random O_DIRECT
# reads spaced SDLAT_GAP ms apart (sdlat's gap_ms argument), so it measures
# the loaded card's read latency - block-layer queueing behind writes
# included - without becoming the load. The sampling loop itself is pinned
# to CPU1 and uses shell builtins only (no fork per sample).
#
# vmstat counters (allocstall, pgsteal/pgscan by source, kswapd_*, pswp*,
# workingset_refault) and /sys/block/mmcblk0/stat are always snapshotted at
# A and B; the host prints the deltas.
#
# Knobs: SCHED (none|kyber|mq-deadline|bfq, default none), KYBER_RLAT
# (read_lat_nsec, default 1000000), DL_REXP (mq-deadline read_expire ms,
# default 100), PRE, MODE (timedemo|attract), QUAKE_ARGS (default -mem 20),
# SETTLE (35), WINDOW (60), STEP (3), SDLAT_N (280), SDLAT_GAP (200),
# TIMEOUT (runsh window, default 330).
set -u
cd "$(dirname "$0")/../.."
L=${1:?label}
SCHED=${SCHED:-none}; KYBER_RLAT=${KYBER_RLAT:-1000000}; DL_REXP=${DL_REXP:-100}
PRE=${PRE:-:}; MODE=${MODE:-timedemo}; QUAKE_ARGS=${QUAKE_ARGS:--mem 20}
SETTLE=${SETTLE:-35}; WINDOW=${WINDOW:-60}; STEP=${STEP:-3}
RING=${RING:-0}; SDLAT=${SDLAT:-0}; PROCS=${PROCS:-0}; LVSTAT=${LVSTAT:-0}
SDLAT_N=${SDLAT_N:-280}; SDLAT_GAP=${SDLAT_GAP:-200}
TIMEOUT=${TIMEOUT:-330}; NORESET=${NORESET:-0}
OUT=artifacts/perf-plan/paging-p1-$L-$(date +%H%M%S); mkdir -p "$OUT"
S=$OUT/run.sh
TD="+timedemo demo1"; [ "$MODE" = attract ] && TD=""
NSTEP=$((WINDOW / STEP))

cat > "$S" <<EOF
# generated by scripts/board/paging-p1.sh ($L) - do not edit by hand
P=/sys/module/dw_mmc/parameters
Q=/sys/block/mmcblk0/queue
echo "UNAME \$(uname -a)"
for p in \$(ps | awk '/[t]iopex|[t]yr-quake|[t]yrquake/ {print \$1}'); do kill -9 \$p 2>/dev/null; done
while :; do read u r < /proc/uptime; [ \${u%%.*} -ge 150 ] && break; sleep 5; done
echo "UPTIME_AT_START \$u"
echo $SCHED > \$Q/scheduler
[ "$SCHED" = kyber ] && echo $KYBER_RLAT > \$Q/iosched/read_lat_nsec
[ "$SCHED" = mq-deadline ] && echo $DL_REXP > \$Q/iosched/read_expire
echo "SCHED \$(cat \$Q/scheduler) \$(for f in \$Q/iosched/*; do [ -r \$f ] && printf '%s=%s ' \${f##*/} \$(cat \$f); done)"
lvpid=\$(ps | awk '/[l]vdesk/ {print \$1; exit}')
echo "LVPID \$lvpid"
lvstat() {
	[ $LVSTAT = 1 ] || return 0
	echo "LVSTAT_BEGIN \$1"
	n0=\$(wc -l < /var/log/lvdesk.log)
	kill -USR1 \$lvpid; sleep 2
	tail -n +\$((n0 + 1)) /var/log/lvdesk.log
	grep -E '^(VmRSS|VmSwap|RssAnon|RssFile|RssShmem)' /proc/\$lvpid/status | tr -s ' ' | tr '\n' ' '; echo
	grep -E 'dri|memfd|SYSV' /proc/\$lvpid/maps
	for x in \$(ps | awk '/[X]org|[X]fbdev/ {print \$1}'); do echo "XSERVER \$x \$(grep -E '^(VmRSS|VmSwap)' /proc/\$x/status | tr -s ' ' | tr '\n' ' ')"; done
	grep -E 'MemFree|MemAvailable|Cma|Shmem:|SwapFree|AnonPages|^Cached|Mapped' /proc/meminfo | tr -s ' ' | tr '\n' ' '; echo
	dmesg | grep -E 'scanout started|kms:|fullscreen' | tail -4
	echo "LVSTAT_END \$1"
}
lvstat desktop
$PRE
echo "PRE_STATUS \$? wsf=\$(cat /proc/sys/vm/watermark_scale_factor) min_free=\$(cat /proc/sys/vm/min_free_kbytes) kswapd_cpus=\$(grep Cpus_allowed_list /proc/\$(ps | awk '/[k]swapd0/ {print \$1}')/status | tr -s ' \t' ' ')"
grep -E 'MemFree|MemAvailable|SwapFree' /proc/meminfo | tr -s ' ' | tr '\n' ' '; echo
cd /root/quake
rm -f /root/-basedir/qconsole.log /root/quake/id1/qconsole.log /root/quake/.tyrquake/id1/qconsole.log
amixer -q sset 'DACL' 110 2>/dev/null; amixer -q sset 'DACR' 110 2>/dev/null
setsid sh -c 'DISPLAY=:0 HOME=/root/quake exec ./tyr-quake-x11 id1 -basedir /root/quake $QUAKE_ARGS -width 320 -height 240 -fullscreen -condebug $TD >/root/quake/td.log 2>&1' </dev/null >/dev/null 2>&1 &
sleep $SETTLE
QP=\$(ps | awk '/[t]yr-quake/ {print \$1}' | head -1)
echo "QPID \${QP:-NONE} \$(grep -a '^Error:' /root/quake/td.log 2>/dev/null | head -1)"
lvstat fullscreen
/root/pin -p 1 \$\$ >/dev/null 2>&1
snap() {
	echo "SNAP_\$1 uptime=\$(cat /proc/uptime)"
	echo "VM_\$1 \$(grep -E '^(allocstall_|pgsteal_|pgscan_|kswapd_|pswp|pgmajfault|workingset_refault|pgrefill|pageoutrun|swap_ra|swpin_zero|swpout_zero|compact_stall|pgfault)' /proc/vmstat | tr '\n' ' ')"
	echo "SD_\$1 \$(cat /sys/block/mmcblk0/stat | tr -s ' ')"
	echo "ST_\$1 \$(grep -E '^(cpu |ctxt)' /proc/stat | tr '\n' ' ')"
	echo "MEM_\$1 \$(grep -E 'MemFree|MemAvailable|SwapFree|Cma' /proc/meminfo | tr -s ' ' | tr '\n' ' ')"
	KP=\$(ps | awk '/[k]swapd0/ {print \$1}')
	echo "K_\$1 \$(awk '{print "utime="\$14, "stime="\$15, "majflt="\$12, "cpu="\$39}' /proc/\$KP/stat 2>/dev/null)"
	[ -n "\$QP" ] && echo "Q_\$1 \$(awk '{print "utime="\$14, "stime="\$15, "majflt="\$12, "cpu="\$39}' /proc/\$QP/stat 2>/dev/null)"
}
procs() {
	# one grep over every status file: one fork, not a read loop per process
	# (the loop form took ~7 s a sample on CPU1 and stretched a 60 s window to 113)
	echo "PROCS_BEGIN \$1"
	grep -E '^(Name|VmRSS|VmSwap):' /proc/[0-9]*/status 2>/dev/null
	echo "PROCS_END \$1"
}
ring() {
	echo "RING_BEGIN \$1"
	echo 0 > \$P/sdtrace_ring; while read -r l; do echo "\$l"; done < \$P/sdtrace_ring
	echo 32 > \$P/sdtrace_ring; while read -r l; do echo "\$l"; done < \$P/sdtrace_ring
	echo 0 > \$P/sdtrace_ring
	echo "RING_END \$1"
}
snap A
echo 0 > \$P/sdtrace
[ $SDLAT = 1 ] && { /root/pin 1 /root/sdlat /dev/mmcblk0 4 $SDLAT_N rand $SDLAT_GAP > /tmp/sdlat.out 2>&1 & }
[ $PROCS = 1 ] && procs 0
i=1; while [ \$i -le $NSTEP ]; do
	sleep $STEP
	[ $RING = 1 ] && ring \$i
	[ $PROCS = 1 ] && [ \$((i % 3)) = 0 ] && procs \$i
	i=\$((i + 1))
done
snap B
echo "SDTRACE_SUM_BEGIN"; cat \$P/sdtrace; echo "SDTRACE_SUM_END"
if [ $SDLAT = 1 ]; then
	j=0; while [ \$j -lt 30 ] && ! grep -q 'min' /tmp/sdlat.out 2>/dev/null; do sleep 2; j=\$((j + 1)); done
	echo "SDLAT \$(cat /tmp/sdlat.out)"
fi
if [ "$MODE" = timedemo ] && [ -n "\$QP" ]; then
	j=0; while [ \$j -lt 40 ]; do grep -aqE "[0-9]+ frames" /root/quake/id1/qconsole.log /root/quake/.tyrquake/id1/qconsole.log 2>/dev/null && break; grep -aq "^Error:" /root/quake/td.log 2>/dev/null && break; sleep 3; j=\$((j + 1)); done
	echo "RESULT \$(grep -ahE '[0-9]+ frames' /root/quake/id1/qconsole.log /root/quake/.tyrquake/id1/qconsole.log 2>/dev/null | head -1)"
fi
echo "QUAKE majflt=\$(awk '{print \$12}' /proc/\$QP/stat 2>/dev/null) \$(grep -aE 'VmRSS|VmSwap' /proc/\$QP/status 2>/dev/null | tr -s ' ' | tr '\n' ' ')"
for p in \$(ps | awk '/[t]yr-quake/ {print \$1}'); do kill -9 \$p 2>/dev/null; done
amixer -q sset 'DACL' 143 2>/dev/null; amixer -q sset 'DACR' 143 2>/dev/null
echo "SCANOUT_FAIL \$(dmesg | grep -ac 'failed to start scanout')"
echo P1_DONE
EOF

echo "paging-p1 [$L] sched=$SCHED mode=$MODE ring=$RING sdlat=$SDLAT procs=$PROCS lvstat=$LVSTAT -> $OUT"
if [ "$NORESET" = 0 ]; then
	python3 scripts/board/reset.py > "$OUT/reset.log" 2>&1 || { echo "reset.py failed"; cat "$OUT/reset.log"; exit 3; }
fi
python3 scripts/board/runsh.py "$S" "$TIMEOUT" 0 2>"$OUT/runsh.err" | tr -d '\r' > "$OUT/run.log"
grep -q 'SERIAL PORT BUSY' "$OUT/runsh.err" "$OUT/run.log" && { echo "SERIAL PORT BUSY - not a dead board"; exit 3; }
grep -q '^NO_SHELL' "$OUT/run.log" && { echo "$(grep -m1 '^NO_SHELL' "$OUT/run.log") - ask alive.py"; exit 3; }
grep -q 'RS_TIMEKILL' "$OUT/run.log" && echo "THE BOARD KILLED THE SCRIPT (TIMEOUT=$TIMEOUT) - half-applied"
grep -q '^P1_DONE' "$OUT/run.log" || echo "WARNING: no P1_DONE marker"
python3 scripts/board/paging-p1.py "$OUT/run.log" | tee "$OUT/summary.txt"
