#!/usr/bin/env python3
"""Generate sigs3.h: the FULL body of each libgcc soft-double routine this
toolchain links, with a byte mask for the few instruction words the linker
fills in (PC-relative data references - only __divdf3 has any).

Every other relocation in these members is an intra-routine branch, whose
bytes are fixed once assembled, so the body in any linked program is the
member's .text byte for byte. The patcher requires the whole body to match
(masked words aside) before it touches anything: no match, no patch.
  python3 mksig3.py <objdump> <objcopy> <ar> <libgcc.a> > sigs3.h
"""
import subprocess, sys, tempfile, os
objdump, objcopy, ar, libgcc = sys.argv[1:5]
WANT = [("muldf3.o", "__muldf3"), ("adddf3.o", "__adddf3"), ("subdf3.o", "__subdf3"),
        ("divdf3.o", "__divdf3"), ("fixdfsi.o", "__fixdfsi"), ("floatsidf.o", "__floatsidf"),
        ("fixunsdfsi.o", "__fixunsdfsi"), ("floatunsidf.o", "__floatunsidf"),
        ("extendsfdf2.o", "__extendsfdf2"), ("truncdfsf2.o", "__truncdfsf2"),
        ("gedf2.o", "__gedf2"), ("ledf2.o", "__ledf2"), ("eqdf2.o", "__eqdf2"),
        ("unorddf2.o", "__unorddf2")]
BRANCH = ("R_RISCV_BRANCH", "R_RISCV_RVC_BRANCH", "R_RISCV_JAL", "R_RISCV_RVC_JUMP")
d = tempfile.mkdtemp(); os.chdir(d)
subprocess.check_call([ar, "x", libgcc] + [m for m, _ in WANT])
print("/* generated by mksig3.py from %s - do not edit */" % os.path.basename(libgcc))
print("struct s31_sig { const char *name; unsigned short len, nmask; const unsigned char *body; const unsigned short *mask; };")
rows, bodies = [], {}
for m, sym in WANT:
    subprocess.check_call([objcopy, "-O", "binary", "-j", ".text", m, m + ".bin"])
    text = open(m + ".bin", "rb").read()
    syms = subprocess.check_output([objdump, "-t", m]).decode()
    off = [int(l.split()[0], 16) for l in syms.splitlines() if l.split() and l.split()[-1] == sym and ".text" in l]
    assert off == [0], (m, sym, off)
    masks = []
    for l in subprocess.check_output([objdump, "-r", "-j", ".text", m]).decode().splitlines():
        p = l.split()
        if len(p) >= 2 and p[1].startswith("R_RISCV_"):
            if p[1] in BRANCH:
                continue
            if p[1] == "R_RISCV_RELAX":
                continue		# the relaxable pair is masked below; if the linker DID relax it, the body length differs and nothing matches
            assert p[1] in ("R_RISCV_PCREL_HI20", "R_RISCV_PCREL_LO12_I"), (m, l)
            masks.append(int(p[0], 16))	# one 4-byte instruction word
    c = sym.strip("_")
    print("static const unsigned char body_%s[%d] = {%s};" % (c, len(text), ",".join("0x%02x" % b for b in text)))
    print("static const unsigned short mask_%s[] = {%s};" % (c, ",".join(str(x) for x in masks) or "0xffff"))
    rows.append('\t{ "%s", %d, %d, body_%s, mask_%s },' % (sym, len(text), len(masks), c, c))
    bodies[sym] = (text, masks)
# no body may equal another under the masks (ge/le differ only late on)
for a in bodies:
    for b in bodies:
        if a < b and len(bodies[a][0]) == len(bodies[b][0]):
            assert bodies[a][0] != bodies[b][0], ("identical bodies", a, b)
    assert bodies[a][0][:2] != b"\x00\x00"
print("#define S31_NSIG %d" % len(rows))
print("static const struct s31_sig s31_sigs[S31_NSIG] = {")
print("\n".join(rows)); print("};")
