#!/usr/bin/env python3
"""Generate sigs.h: the first bytes of each libgcc soft-double routine.

The preload library finds these byte strings in a program's text and redirects
the routine. The prefix stops at the first relocation that is not a local
branch (a relaxable auipc/call would change the bytes after it), and the
routine must start its member's .text. Run inside the build container:
  python3 mksig.py <objdump> <objcopy> <ar> <libgcc.a> > sigs.h
"""
import subprocess, sys, tempfile, os, re
objdump, objcopy, ar, libgcc = sys.argv[1:5]
WANT = {  # member -> (routine symbol, our replacement or None)
    "muldf3.o": "__muldf3", "adddf3.o": "__adddf3", "subdf3.o": "__subdf3",
    "divdf3.o": "__divdf3", "fixdfsi.o": "__fixdfsi", "floatsidf.o": "__floatsidf",
    "fixunsdfsi.o": "__fixunsdfsi", "floatunsidf.o": "__floatunsidf",
    "extendsfdf2.o": "__extendsfdf2", "truncdfsf2.o": "__truncdfsf2",
}
d = tempfile.mkdtemp(); os.chdir(d)
subprocess.check_call([ar, "x", libgcc] + list(WANT))
print("/* generated by mksig.py from %s - do not edit */" % os.path.basename(libgcc))
print("struct s31fp_sig { const char *name; unsigned len; unsigned total; const unsigned char *bytes; };")
rows = []
for m, sym in WANT.items():
    subprocess.check_call([objcopy, "-O", "binary", "-j", ".text", m, m + ".bin"])
    text = open(m + ".bin", "rb").read()
    syms = subprocess.check_output([objdump, "-t", m]).decode()
    off = None
    for l in syms.splitlines():
        p = l.split()
        if p and p[-1] == sym and ".text" in l:
            off = int(p[0], 16)
    assert off == 0, (m, sym, off)
    rel = subprocess.check_output([objdump, "-r", "-j", ".text", m]).decode()
    stop = len(text)
    for l in rel.splitlines():
        p = l.split()
        if len(p) >= 2 and p[1].startswith("R_RISCV_") and p[1] not in (
                "R_RISCV_BRANCH", "R_RISCV_RVC_BRANCH", "R_RISCV_JAL",
                "R_RISCV_RVC_JUMP", "R_RISCV_RELAX", "R_RISCV_ALIGN"):
            stop = min(stop, int(p[0], 16))
        if len(p) >= 2 and p[1] == "R_RISCV_ALIGN":
            stop = min(stop, int(p[0], 16))
    n = min(stop, 64) & ~1
    assert n >= 24, (m, n)
    c = sym.strip("_")
    print("static const unsigned char sig_%s[] = {%s};" % (c, ",".join("0x%02x" % b for b in text[:n])))
    rows.append('\t{ "%s", %d, %d, sig_%s },' % (sym, n, len(text), c))
print("static const struct s31fp_sig s31fp_sigs[] = {")
print("\n".join(rows)); print("};")
