/* s31: every public entry point TinyGL defines is renamed to tgl_<name> so the
 * Khronos ABI layer in gl/api/ is the only thing that exports GL names.
 * Included first by include/GL/gl.h. Regenerate if a TinyGL gl* function is added. */
#ifndef TGL_RENAME_H
#define TGL_RENAME_H
#define glArrayElement         tgl_glArrayElement
#define glBegin                tgl_glBegin
#define glBindTexture          tgl_glBindTexture
#define glCallList             tgl_glCallList
#define glClear                tgl_glClear
#define glClearColor           tgl_glClearColor
#define glClearDepth           tgl_glClearDepth
#define glClose                tgl_glClose
#define glColor3f              tgl_glColor3f
#define glColor3fv             tgl_glColor3fv
#define glColor3ub             tgl_glColor3ub
#define glColor3ubv            tgl_glColor3ubv
#define glColor4f              tgl_glColor4f
#define glColor4fv             tgl_glColor4fv
#define glColor4ub             tgl_glColor4ub
#define glColor4ubv            tgl_glColor4ubv
#define glColorMaterial        tgl_glColorMaterial
#define glColorPointer         tgl_glColorPointer
#define glCullFace             tgl_glCullFace
#define glDebug                tgl_glDebug
#define glDeleteLists          tgl_glDeleteLists
#define glDeleteTextures       tgl_glDeleteTextures
#define glDisable              tgl_glDisable
#define glDisableClientState   tgl_glDisableClientState
#define glDrawArrays           tgl_glDrawArrays
#define glDrawElements         tgl_glDrawElements
#define glEdgeFlag             tgl_glEdgeFlag
#define glEnable               tgl_glEnable
#define glEnableClientState    tgl_glEnableClientState
#define glEnd                  tgl_glEnd
#define glEndList              tgl_glEndList
#define glFlush                tgl_glFlush
#define glFrontFace            tgl_glFrontFace
#define glFrustum              tgl_glFrustum
#define glGenLists             tgl_glGenLists
#define glGenTextures          tgl_glGenTextures
#define glGetFloatv            tgl_glGetFloatv
#define glGetIntegerv          tgl_glGetIntegerv
#define glHint                 tgl_glHint
#define glInit                 tgl_glInit
#define glInitNames            tgl_glInitNames
#define glInitTextures         tgl_glInitTextures
#define glEndTextures          tgl_glEndTextures
#define glIsList               tgl_glIsList
#define glLightf               tgl_glLightf
#define glLightfv              tgl_glLightfv
#define glLightModelfv         tgl_glLightModelfv
#define glLightModeli          tgl_glLightModeli
#define glLoadIdentity         tgl_glLoadIdentity
#define glLoadMatrixf          tgl_glLoadMatrixf
#define glLoadName             tgl_glLoadName
#define glMaterialf            tgl_glMaterialf
#define glMaterialfv           tgl_glMaterialfv
#define glMatrixMode           tgl_glMatrixMode
#define glMultMatrixf          tgl_glMultMatrixf
#define glNewList              tgl_glNewList
#define glNormal3f             tgl_glNormal3f
#define glNormal3fv            tgl_glNormal3fv
#define glNormalPointer        tgl_glNormalPointer
#define glOrtho                tgl_glOrtho
#define glPixelStorei          tgl_glPixelStorei
#define glPolygonMode          tgl_glPolygonMode
#define glPolygonOffset        tgl_glPolygonOffset
#define glPopMatrix            tgl_glPopMatrix
#define glPopName              tgl_glPopName
#define glPushMatrix           tgl_glPushMatrix
#define glPushName             tgl_glPushName
#define glRenderMode           tgl_glRenderMode
#define glRotatef              tgl_glRotatef
#define glScalef               tgl_glScalef
#define glSelectBuffer         tgl_glSelectBuffer
#define glShadeModel           tgl_glShadeModel
#define glTexCoord2f           tgl_glTexCoord2f
#define glTexCoord2fv          tgl_glTexCoord2fv
#define glTexCoord4f           tgl_glTexCoord4f
#define glTexCoordPointer      tgl_glTexCoordPointer
#define glTexEnvi              tgl_glTexEnvi
#define glTexImage2D           tgl_glTexImage2D
#define glTexParameteri        tgl_glTexParameteri
#define glTranslatef           tgl_glTranslatef
#define glVertex2f             tgl_glVertex2f
#define glVertex3f             tgl_glVertex3f
#define glVertex3fv            tgl_glVertex3fv
#define glVertex4f             tgl_glVertex4f
#define glVertexPointer        tgl_glVertexPointer
#define glViewport             tgl_glViewport
#endif
