#!/usr/bin/env python3
"""
Extract the bytes of a data symbol from an ELF shared library into a C array.

Some Xt resource names are not string literals: StringDefs.h defines
XtNlabel as ((String)&XtStrings[429]), so the offset is compiled into every
application. A replacement libXt must therefore reproduce that table byte for
byte - the strings AND their positions. Guessing is not an option and
rebuilding it by hand would be 400 lines of error-prone constants, so the real
table is lifted out of the real library.

This copies data, not code: the table is a list of resource names like
"label" and "foreground" that the protocol and the header both already
publish.

  python3 tools/extract-symbol.py libXt.so.6.0.0 XtStrings XtShellStrings > out.h
"""
import struct
import sys


def load(path):
    b = open(path, "rb").read()
    if b[:4] != b"\x7fELF" or b[4] != 1:
        sys.exit("%s: not a 32-bit ELF" % path)
    shoff, = struct.unpack_from("<I", b, 0x20)
    shentsize, shnum, shstrndx = struct.unpack_from("<HHH", b, 0x2E)
    secs = []
    for i in range(shnum):
        o = shoff + i * shentsize
        name, typ, flags, addr, off, size, link, info, align, entsize = \
            struct.unpack_from("<10I", b, o)
        secs.append(dict(name=name, type=typ, addr=addr, off=off, size=size,
                         link=link, entsize=entsize))
    return b, secs


def symbols(b, secs):
    out = {}
    for s in secs:
        if s["type"] not in (2, 11) or not s["entsize"]:   # SYMTAB, DYNSYM
            continue
        strtab = secs[s["link"]]
        for k in range(s["size"] // s["entsize"]):
            o = s["off"] + k * s["entsize"]
            nm, val, sz, info, other, shndx = struct.unpack_from("<IIIBBH", b, o)
            if not sz:
                continue
            e = b.index(b"\0", strtab["off"] + nm)
            name = b[strtab["off"] + nm:e].decode()
            if name:
                out.setdefault(name, (val, sz))
    return out


def main(lib, names):
    b, secs = load(lib)
    syms = symbols(b, secs)
    print("/* SPDX-License-Identifier: GPL-2.0-only */")
    print("/* Generated by tools/extract-symbol.py from %s. Do not edit. */"
          % lib.split("/")[-1])
    for n in names:
        if n not in syms:
            sys.exit("%s: no symbol %s" % (lib, n))
        addr, size = syms[n]
        sec = next(s for s in secs
                   if s["addr"] and s["addr"] <= addr < s["addr"] + s["size"])
        off = sec["off"] + (addr - sec["addr"])
        data = b[off:off + size]
        print("\n/* %s: %d bytes, offsets are compiled into every client. */"
              % (n, size))
        print("const char %s[%d] = {" % (n, size))
        for i in range(0, len(data), 12):
            row = ", ".join("0x%02x" % c for c in data[i:i + 12])
            print("\t%s," % row)
        print("};")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2:])
