#!/usr/bin/env python3
"""
Generate the stub half of xlite - our small libX11 replacement.

Every symbol the toolkit may call has to EXIST, or the dynamic linker refuses
to start the client and we learn nothing. So anything not implemented by hand
becomes a stub that:

  - logs once, by name, saying it is missing
  - counts how often it was called
  - returns a benign zero and lets the client carry on

That last part is deliberate. Failing hard on the first gap tells you one name
per run; carrying on collects the whole list in a single run, which is how the
X shim's own BadImplementation reporting works and what made xcalc a two-line
to-do rather than an investigation.

Stubs are declared as variadic-ignoring `long f(long...)`. On this ABI the
arguments arrive in registers and are simply not read, and every Xlib entry
point returns a scalar or a pointer, never a struct by value.

  python3 tools/mkxlitestubs.py xlite/symbols.txt xlite/stubs.c xlite/*.c
"""
import re
import sys

# Data symbols, not functions: the thread-locking hooks Xlib exports. NULL is
# the documented "no threads initialised" value, which is what we are.
DATA = {"_XLockMutex_fn", "_XUnlockMutex_fn", "_Xglobal_lock"}


def implemented(paths):
    """Names defined by hand, marked with XLITE_IMPL in the source."""
    got = set()
    for p in paths:
        for line in open(p):
            m = re.search(r"XLITE_IMPL\((\w+)\)", line)
            if m:
                got.add(m.group(1))
    return got


def main(symfile, out, sources):
    want = [l.strip() for l in open(symfile) if l.strip()]
    have = implemented(sources)
    todo = [s for s in want if s not in have and s not in DATA]

    f = ["/* SPDX-License-Identifier: GPL-2.0-only */",
         "/* Generated by tools/mkxlitestubs.py. Do not edit. */",
         "/*",
         " * Deliberately does NOT include Xlib.h: these stubs are declared as",
         " * `long f(long...)` and would clash with the real prototypes. Only",
         " * the reporting hook is needed here.",
         " */",
         "void xlite_missing(int idx, const char *name);", "",
         "/* Thread-locking hooks. NULL means \"threads never initialised\". */",
         "void (*_XLockMutex_fn)(void *) = 0;",
         "void (*_XUnlockMutex_fn)(void *) = 0;",
         "void *_Xglobal_lock = 0;", ""]
    for i, name in enumerate(todo):
        f.append("long %s(long a, long b, long c, long d, long e, long g)" % name)
        f.append("{")
        f.append("\t(void)a; (void)b; (void)c; (void)d; (void)e; (void)g;")
        f.append('\txlite_missing(%d, "%s");' % (i, name))
        f.append("\treturn 0;")
        f.append("}")
        f.append("")
    f.append("const int xlite_nstubs = %d;" % len(todo))
    f.append("")
    open(out, "w").write("\n".join(f))
    print("%d symbols required, %d implemented, %d stubbed -> %s"
          % (len(want), len(have), len(todo), out))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3:])
