#!/usr/bin/env python3
"""
Turn the kernel's 8x8 console font into a C table for the X11 shim.

The shim's QueryFont already claims a fixed 8x8 face with ascent 7 and descent
1. This makes that claim TRUE rather than synthetic, which matters more than it
sounds: a toolkit lays its widgets out from the metrics the server reports, so
metrics that do not match the glyphs give a correct-looking window full of
clipped or overlapping text.

Source is lib/fonts/font_8x8.c from the kernel tree we already build - same
GPL-2.0 as the shim - so no font package, no font file on the card, and 760
bytes of glyph data that live in XIP flash at zero RSS.

  python3 tools/mkxshimfont.py linux-71-port/lib/fonts/font_8x8.c \
      lvdesk/xshim_font.h
"""
import re
import sys

FIRST, LAST = 0, 255


def main(src, dst):
    text = open(src).read()
    # The table is a flat list of 2048 byte literals, one per line, with the
    # character index in a comment. Take the literals in order.
    body = text[text.index("FONTDATAMAX"):]
    vals = [int(v, 16) for v in re.findall(r"0x([0-9a-fA-F]{2}),", body)]
    if len(vals) < 256 * 8:
        sys.exit("expected 2048 bytes, found %d" % len(vals))

    out = ["/* SPDX-License-Identifier: GPL-2.0-only */",
           "/*",
           " * Generated by tools/mkxshimfont.py from the kernel's",
           " * lib/fonts/font_8x8.c. Do not edit.",
           " *",
           " * CP437 %d..%d, 8x8, one byte per row, MSB leftmost." % (FIRST, LAST),
           " * Ascent 7, descent 1: row r sits at baseline - 7 + r.",
           " */",
           "#ifndef LVDESK_XSHIM_FONT_H",
           "#define LVDESK_XSHIM_FONT_H",
           "",
           "#define XFONT_FIRST\t%d" % FIRST,
           "#define XFONT_LAST\t%d" % LAST,
           "#define XFONT_W\t\t8",
           "#define XFONT_H\t\t8",
           "#define XFONT_ASCENT\t7",
           "#define XFONT_DESCENT\t1",
           "",
           "static const unsigned char xfont_bits[%d][8] = {"
           % (LAST - FIRST + 1)]
    for c in range(FIRST, LAST + 1):
        rows = vals[c * 8:(c + 1) * 8]
        ch = chr(c) if 32 <= c < 127 else "."
        ch = ch.replace("\\", "\\\\").replace("'", "\\'")
        out.append("\t{ %s }, /* '%s' */"
                   % (", ".join("0x%02x" % r for r in rows), ch))
    out += ["};", "", "#endif /* LVDESK_XSHIM_FONT_H */", ""]
    open(dst, "w").write("\n".join(out))
    print("wrote %s: %d glyphs" % (dst, LAST - FIRST + 1))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
