/* GENERATED by mkattrib.py - do not edit; see that script. s31, MIT. */
#include "s31_api.h"

void GLAPIENTRY glVertex2s(GLshort x, GLshort y)
{
	tgl_glVertex4f((GLfloat)x, (GLfloat)y, 0.0f, 1.0f);
}
void GLAPIENTRY glVertex2sv(const GLshort *v)
{
	tgl_glVertex4f((GLfloat)v[0], (GLfloat)v[1], 0.0f, 1.0f);
}

void GLAPIENTRY glVertex2i(GLint x, GLint y)
{
	tgl_glVertex4f((GLfloat)x, (GLfloat)y, 0.0f, 1.0f);
}
void GLAPIENTRY glVertex2iv(const GLint *v)
{
	tgl_glVertex4f((GLfloat)v[0], (GLfloat)v[1], 0.0f, 1.0f);
}

void GLAPIENTRY glVertex2f(GLfloat x, GLfloat y)
{
	tgl_glVertex4f(x, y, 0.0f, 1.0f);
}
void GLAPIENTRY glVertex2fv(const GLfloat *v)
{
	tgl_glVertex4f(v[0], v[1], 0.0f, 1.0f);
}

void GLAPIENTRY glVertex2d(GLdouble x, GLdouble y)
{
	tgl_glVertex4f(s31_d2f(x), s31_d2f(y), 0.0f, 1.0f);
}
void GLAPIENTRY glVertex2dv(const GLdouble *v)
{
	tgl_glVertex4f(s31_d2f(v[0]), s31_d2f(v[1]), 0.0f, 1.0f);
}

void GLAPIENTRY glVertex3s(GLshort x, GLshort y, GLshort z)
{
	tgl_glVertex4f((GLfloat)x, (GLfloat)y, (GLfloat)z, 1.0f);
}
void GLAPIENTRY glVertex3sv(const GLshort *v)
{
	tgl_glVertex4f((GLfloat)v[0], (GLfloat)v[1], (GLfloat)v[2], 1.0f);
}

void GLAPIENTRY glVertex3i(GLint x, GLint y, GLint z)
{
	tgl_glVertex4f((GLfloat)x, (GLfloat)y, (GLfloat)z, 1.0f);
}
void GLAPIENTRY glVertex3iv(const GLint *v)
{
	tgl_glVertex4f((GLfloat)v[0], (GLfloat)v[1], (GLfloat)v[2], 1.0f);
}

void GLAPIENTRY glVertex3f(GLfloat x, GLfloat y, GLfloat z)
{
	tgl_glVertex4f(x, y, z, 1.0f);
}
void GLAPIENTRY glVertex3fv(const GLfloat *v)
{
	tgl_glVertex4f(v[0], v[1], v[2], 1.0f);
}

void GLAPIENTRY glVertex3d(GLdouble x, GLdouble y, GLdouble z)
{
	tgl_glVertex4f(s31_d2f(x), s31_d2f(y), s31_d2f(z), 1.0f);
}
void GLAPIENTRY glVertex3dv(const GLdouble *v)
{
	tgl_glVertex4f(s31_d2f(v[0]), s31_d2f(v[1]), s31_d2f(v[2]), 1.0f);
}

void GLAPIENTRY glVertex4s(GLshort x, GLshort y, GLshort z, GLshort w)
{
	tgl_glVertex4f((GLfloat)x, (GLfloat)y, (GLfloat)z, (GLfloat)w);
}
void GLAPIENTRY glVertex4sv(const GLshort *v)
{
	tgl_glVertex4f((GLfloat)v[0], (GLfloat)v[1], (GLfloat)v[2], (GLfloat)v[3]);
}

void GLAPIENTRY glVertex4i(GLint x, GLint y, GLint z, GLint w)
{
	tgl_glVertex4f((GLfloat)x, (GLfloat)y, (GLfloat)z, (GLfloat)w);
}
void GLAPIENTRY glVertex4iv(const GLint *v)
{
	tgl_glVertex4f((GLfloat)v[0], (GLfloat)v[1], (GLfloat)v[2], (GLfloat)v[3]);
}

void GLAPIENTRY glVertex4f(GLfloat x, GLfloat y, GLfloat z, GLfloat w)
{
	tgl_glVertex4f(x, y, z, w);
}
void GLAPIENTRY glVertex4fv(const GLfloat *v)
{
	tgl_glVertex4f(v[0], v[1], v[2], v[3]);
}

void GLAPIENTRY glVertex4d(GLdouble x, GLdouble y, GLdouble z, GLdouble w)
{
	tgl_glVertex4f(s31_d2f(x), s31_d2f(y), s31_d2f(z), s31_d2f(w));
}
void GLAPIENTRY glVertex4dv(const GLdouble *v)
{
	tgl_glVertex4f(s31_d2f(v[0]), s31_d2f(v[1]), s31_d2f(v[2]), s31_d2f(v[3]));
}

void GLAPIENTRY glNormal3b(GLbyte x, GLbyte y, GLbyte z)
{
	tgl_glNormal3f(((2 * (GLint)x + 1) * (1.0f / 255.0f)), ((2 * (GLint)y + 1) * (1.0f / 255.0f)), ((2 * (GLint)z + 1) * (1.0f / 255.0f)));
}
void GLAPIENTRY glNormal3bv(const GLbyte *v)
{
	tgl_glNormal3f(((2 * (GLint)v[0] + 1) * (1.0f / 255.0f)), ((2 * (GLint)v[1] + 1) * (1.0f / 255.0f)), ((2 * (GLint)v[2] + 1) * (1.0f / 255.0f)));
}

void GLAPIENTRY glNormal3s(GLshort x, GLshort y, GLshort z)
{
	tgl_glNormal3f(((2 * (GLint)x + 1) * (1.0f / 65535.0f)), ((2 * (GLint)y + 1) * (1.0f / 65535.0f)), ((2 * (GLint)z + 1) * (1.0f / 65535.0f)));
}
void GLAPIENTRY glNormal3sv(const GLshort *v)
{
	tgl_glNormal3f(((2 * (GLint)v[0] + 1) * (1.0f / 65535.0f)), ((2 * (GLint)v[1] + 1) * (1.0f / 65535.0f)), ((2 * (GLint)v[2] + 1) * (1.0f / 65535.0f)));
}

void GLAPIENTRY glNormal3i(GLint x, GLint y, GLint z)
{
	tgl_glNormal3f(((2.0f * (GLfloat)x + 1.0f) * (1.0f / 4294967295.0f)), ((2.0f * (GLfloat)y + 1.0f) * (1.0f / 4294967295.0f)), ((2.0f * (GLfloat)z + 1.0f) * (1.0f / 4294967295.0f)));
}
void GLAPIENTRY glNormal3iv(const GLint *v)
{
	tgl_glNormal3f(((2.0f * (GLfloat)v[0] + 1.0f) * (1.0f / 4294967295.0f)), ((2.0f * (GLfloat)v[1] + 1.0f) * (1.0f / 4294967295.0f)), ((2.0f * (GLfloat)v[2] + 1.0f) * (1.0f / 4294967295.0f)));
}

void GLAPIENTRY glNormal3f(GLfloat x, GLfloat y, GLfloat z)
{
	tgl_glNormal3f(x, y, z);
}
void GLAPIENTRY glNormal3fv(const GLfloat *v)
{
	tgl_glNormal3f(v[0], v[1], v[2]);
}

void GLAPIENTRY glNormal3d(GLdouble x, GLdouble y, GLdouble z)
{
	tgl_glNormal3f(s31_d2f(x), s31_d2f(y), s31_d2f(z));
}
void GLAPIENTRY glNormal3dv(const GLdouble *v)
{
	tgl_glNormal3f(s31_d2f(v[0]), s31_d2f(v[1]), s31_d2f(v[2]));
}

void GLAPIENTRY glColor3b(GLbyte r, GLbyte g, GLbyte b)
{
	tgl_glColor4f(((2 * (GLint)r + 1) * (1.0f / 255.0f)), ((2 * (GLint)g + 1) * (1.0f / 255.0f)), ((2 * (GLint)b + 1) * (1.0f / 255.0f)), 1.0f);
}
void GLAPIENTRY glColor3bv(const GLbyte *v)
{
	tgl_glColor4f(((2 * (GLint)v[0] + 1) * (1.0f / 255.0f)), ((2 * (GLint)v[1] + 1) * (1.0f / 255.0f)), ((2 * (GLint)v[2] + 1) * (1.0f / 255.0f)), 1.0f);
}

void GLAPIENTRY glColor3s(GLshort r, GLshort g, GLshort b)
{
	tgl_glColor4f(((2 * (GLint)r + 1) * (1.0f / 65535.0f)), ((2 * (GLint)g + 1) * (1.0f / 65535.0f)), ((2 * (GLint)b + 1) * (1.0f / 65535.0f)), 1.0f);
}
void GLAPIENTRY glColor3sv(const GLshort *v)
{
	tgl_glColor4f(((2 * (GLint)v[0] + 1) * (1.0f / 65535.0f)), ((2 * (GLint)v[1] + 1) * (1.0f / 65535.0f)), ((2 * (GLint)v[2] + 1) * (1.0f / 65535.0f)), 1.0f);
}

void GLAPIENTRY glColor3i(GLint r, GLint g, GLint b)
{
	tgl_glColor4f(((2.0f * (GLfloat)r + 1.0f) * (1.0f / 4294967295.0f)), ((2.0f * (GLfloat)g + 1.0f) * (1.0f / 4294967295.0f)), ((2.0f * (GLfloat)b + 1.0f) * (1.0f / 4294967295.0f)), 1.0f);
}
void GLAPIENTRY glColor3iv(const GLint *v)
{
	tgl_glColor4f(((2.0f * (GLfloat)v[0] + 1.0f) * (1.0f / 4294967295.0f)), ((2.0f * (GLfloat)v[1] + 1.0f) * (1.0f / 4294967295.0f)), ((2.0f * (GLfloat)v[2] + 1.0f) * (1.0f / 4294967295.0f)), 1.0f);
}

void GLAPIENTRY glColor3f(GLfloat r, GLfloat g, GLfloat b)
{
	tgl_glColor4f(r, g, b, 1.0f);
}
void GLAPIENTRY glColor3fv(const GLfloat *v)
{
	tgl_glColor4f(v[0], v[1], v[2], 1.0f);
}

void GLAPIENTRY glColor3d(GLdouble r, GLdouble g, GLdouble b)
{
	tgl_glColor4f(s31_d2f(r), s31_d2f(g), s31_d2f(b), 1.0f);
}
void GLAPIENTRY glColor3dv(const GLdouble *v)
{
	tgl_glColor4f(s31_d2f(v[0]), s31_d2f(v[1]), s31_d2f(v[2]), 1.0f);
}

void GLAPIENTRY glColor3ub(GLubyte r, GLubyte g, GLubyte b)
{
	tgl_glColor4f(((GLfloat)r * (1.0f / 255.0f)), ((GLfloat)g * (1.0f / 255.0f)), ((GLfloat)b * (1.0f / 255.0f)), 1.0f);
}
void GLAPIENTRY glColor3ubv(const GLubyte *v)
{
	tgl_glColor4f(((GLfloat)v[0] * (1.0f / 255.0f)), ((GLfloat)v[1] * (1.0f / 255.0f)), ((GLfloat)v[2] * (1.0f / 255.0f)), 1.0f);
}

void GLAPIENTRY glColor3us(GLushort r, GLushort g, GLushort b)
{
	tgl_glColor4f(((GLfloat)r * (1.0f / 65535.0f)), ((GLfloat)g * (1.0f / 65535.0f)), ((GLfloat)b * (1.0f / 65535.0f)), 1.0f);
}
void GLAPIENTRY glColor3usv(const GLushort *v)
{
	tgl_glColor4f(((GLfloat)v[0] * (1.0f / 65535.0f)), ((GLfloat)v[1] * (1.0f / 65535.0f)), ((GLfloat)v[2] * (1.0f / 65535.0f)), 1.0f);
}

void GLAPIENTRY glColor3ui(GLuint r, GLuint g, GLuint b)
{
	tgl_glColor4f(((GLfloat)r * (1.0f / 4294967295.0f)), ((GLfloat)g * (1.0f / 4294967295.0f)), ((GLfloat)b * (1.0f / 4294967295.0f)), 1.0f);
}
void GLAPIENTRY glColor3uiv(const GLuint *v)
{
	tgl_glColor4f(((GLfloat)v[0] * (1.0f / 4294967295.0f)), ((GLfloat)v[1] * (1.0f / 4294967295.0f)), ((GLfloat)v[2] * (1.0f / 4294967295.0f)), 1.0f);
}

void GLAPIENTRY glColor4b(GLbyte r, GLbyte g, GLbyte b, GLbyte a)
{
	tgl_glColor4f(((2 * (GLint)r + 1) * (1.0f / 255.0f)), ((2 * (GLint)g + 1) * (1.0f / 255.0f)), ((2 * (GLint)b + 1) * (1.0f / 255.0f)), ((2 * (GLint)a + 1) * (1.0f / 255.0f)));
}
void GLAPIENTRY glColor4bv(const GLbyte *v)
{
	tgl_glColor4f(((2 * (GLint)v[0] + 1) * (1.0f / 255.0f)), ((2 * (GLint)v[1] + 1) * (1.0f / 255.0f)), ((2 * (GLint)v[2] + 1) * (1.0f / 255.0f)), ((2 * (GLint)v[3] + 1) * (1.0f / 255.0f)));
}

void GLAPIENTRY glColor4s(GLshort r, GLshort g, GLshort b, GLshort a)
{
	tgl_glColor4f(((2 * (GLint)r + 1) * (1.0f / 65535.0f)), ((2 * (GLint)g + 1) * (1.0f / 65535.0f)), ((2 * (GLint)b + 1) * (1.0f / 65535.0f)), ((2 * (GLint)a + 1) * (1.0f / 65535.0f)));
}
void GLAPIENTRY glColor4sv(const GLshort *v)
{
	tgl_glColor4f(((2 * (GLint)v[0] + 1) * (1.0f / 65535.0f)), ((2 * (GLint)v[1] + 1) * (1.0f / 65535.0f)), ((2 * (GLint)v[2] + 1) * (1.0f / 65535.0f)), ((2 * (GLint)v[3] + 1) * (1.0f / 65535.0f)));
}

void GLAPIENTRY glColor4i(GLint r, GLint g, GLint b, GLint a)
{
	tgl_glColor4f(((2.0f * (GLfloat)r + 1.0f) * (1.0f / 4294967295.0f)), ((2.0f * (GLfloat)g + 1.0f) * (1.0f / 4294967295.0f)), ((2.0f * (GLfloat)b + 1.0f) * (1.0f / 4294967295.0f)), ((2.0f * (GLfloat)a + 1.0f) * (1.0f / 4294967295.0f)));
}
void GLAPIENTRY glColor4iv(const GLint *v)
{
	tgl_glColor4f(((2.0f * (GLfloat)v[0] + 1.0f) * (1.0f / 4294967295.0f)), ((2.0f * (GLfloat)v[1] + 1.0f) * (1.0f / 4294967295.0f)), ((2.0f * (GLfloat)v[2] + 1.0f) * (1.0f / 4294967295.0f)), ((2.0f * (GLfloat)v[3] + 1.0f) * (1.0f / 4294967295.0f)));
}

void GLAPIENTRY glColor4f(GLfloat r, GLfloat g, GLfloat b, GLfloat a)
{
	tgl_glColor4f(r, g, b, a);
}
void GLAPIENTRY glColor4fv(const GLfloat *v)
{
	tgl_glColor4f(v[0], v[1], v[2], v[3]);
}

void GLAPIENTRY glColor4d(GLdouble r, GLdouble g, GLdouble b, GLdouble a)
{
	tgl_glColor4f(s31_d2f(r), s31_d2f(g), s31_d2f(b), s31_d2f(a));
}
void GLAPIENTRY glColor4dv(const GLdouble *v)
{
	tgl_glColor4f(s31_d2f(v[0]), s31_d2f(v[1]), s31_d2f(v[2]), s31_d2f(v[3]));
}

void GLAPIENTRY glColor4ub(GLubyte r, GLubyte g, GLubyte b, GLubyte a)
{
	tgl_glColor4f(((GLfloat)r * (1.0f / 255.0f)), ((GLfloat)g * (1.0f / 255.0f)), ((GLfloat)b * (1.0f / 255.0f)), ((GLfloat)a * (1.0f / 255.0f)));
}
void GLAPIENTRY glColor4ubv(const GLubyte *v)
{
	tgl_glColor4f(((GLfloat)v[0] * (1.0f / 255.0f)), ((GLfloat)v[1] * (1.0f / 255.0f)), ((GLfloat)v[2] * (1.0f / 255.0f)), ((GLfloat)v[3] * (1.0f / 255.0f)));
}

void GLAPIENTRY glColor4us(GLushort r, GLushort g, GLushort b, GLushort a)
{
	tgl_glColor4f(((GLfloat)r * (1.0f / 65535.0f)), ((GLfloat)g * (1.0f / 65535.0f)), ((GLfloat)b * (1.0f / 65535.0f)), ((GLfloat)a * (1.0f / 65535.0f)));
}
void GLAPIENTRY glColor4usv(const GLushort *v)
{
	tgl_glColor4f(((GLfloat)v[0] * (1.0f / 65535.0f)), ((GLfloat)v[1] * (1.0f / 65535.0f)), ((GLfloat)v[2] * (1.0f / 65535.0f)), ((GLfloat)v[3] * (1.0f / 65535.0f)));
}

void GLAPIENTRY glColor4ui(GLuint r, GLuint g, GLuint b, GLuint a)
{
	tgl_glColor4f(((GLfloat)r * (1.0f / 4294967295.0f)), ((GLfloat)g * (1.0f / 4294967295.0f)), ((GLfloat)b * (1.0f / 4294967295.0f)), ((GLfloat)a * (1.0f / 4294967295.0f)));
}
void GLAPIENTRY glColor4uiv(const GLuint *v)
{
	tgl_glColor4f(((GLfloat)v[0] * (1.0f / 4294967295.0f)), ((GLfloat)v[1] * (1.0f / 4294967295.0f)), ((GLfloat)v[2] * (1.0f / 4294967295.0f)), ((GLfloat)v[3] * (1.0f / 4294967295.0f)));
}

void GLAPIENTRY glTexCoord1s(GLshort s)
{
	tgl_glTexCoord4f((GLfloat)s, 0.0f, 0.0f, 1.0f);
}
void GLAPIENTRY glTexCoord1sv(const GLshort *v)
{
	tgl_glTexCoord4f((GLfloat)v[0], 0.0f, 0.0f, 1.0f);
}

void GLAPIENTRY glTexCoord1i(GLint s)
{
	tgl_glTexCoord4f((GLfloat)s, 0.0f, 0.0f, 1.0f);
}
void GLAPIENTRY glTexCoord1iv(const GLint *v)
{
	tgl_glTexCoord4f((GLfloat)v[0], 0.0f, 0.0f, 1.0f);
}

void GLAPIENTRY glTexCoord1f(GLfloat s)
{
	tgl_glTexCoord4f(s, 0.0f, 0.0f, 1.0f);
}
void GLAPIENTRY glTexCoord1fv(const GLfloat *v)
{
	tgl_glTexCoord4f(v[0], 0.0f, 0.0f, 1.0f);
}

void GLAPIENTRY glTexCoord1d(GLdouble s)
{
	tgl_glTexCoord4f(s31_d2f(s), 0.0f, 0.0f, 1.0f);
}
void GLAPIENTRY glTexCoord1dv(const GLdouble *v)
{
	tgl_glTexCoord4f(s31_d2f(v[0]), 0.0f, 0.0f, 1.0f);
}

void GLAPIENTRY glTexCoord2s(GLshort s, GLshort t)
{
	tgl_glTexCoord4f((GLfloat)s, (GLfloat)t, 0.0f, 1.0f);
}
void GLAPIENTRY glTexCoord2sv(const GLshort *v)
{
	tgl_glTexCoord4f((GLfloat)v[0], (GLfloat)v[1], 0.0f, 1.0f);
}

void GLAPIENTRY glTexCoord2i(GLint s, GLint t)
{
	tgl_glTexCoord4f((GLfloat)s, (GLfloat)t, 0.0f, 1.0f);
}
void GLAPIENTRY glTexCoord2iv(const GLint *v)
{
	tgl_glTexCoord4f((GLfloat)v[0], (GLfloat)v[1], 0.0f, 1.0f);
}

void GLAPIENTRY glTexCoord2f(GLfloat s, GLfloat t)
{
	tgl_glTexCoord4f(s, t, 0.0f, 1.0f);
}
void GLAPIENTRY glTexCoord2fv(const GLfloat *v)
{
	tgl_glTexCoord4f(v[0], v[1], 0.0f, 1.0f);
}

void GLAPIENTRY glTexCoord2d(GLdouble s, GLdouble t)
{
	tgl_glTexCoord4f(s31_d2f(s), s31_d2f(t), 0.0f, 1.0f);
}
void GLAPIENTRY glTexCoord2dv(const GLdouble *v)
{
	tgl_glTexCoord4f(s31_d2f(v[0]), s31_d2f(v[1]), 0.0f, 1.0f);
}

void GLAPIENTRY glTexCoord3s(GLshort s, GLshort t, GLshort r)
{
	tgl_glTexCoord4f((GLfloat)s, (GLfloat)t, (GLfloat)r, 1.0f);
}
void GLAPIENTRY glTexCoord3sv(const GLshort *v)
{
	tgl_glTexCoord4f((GLfloat)v[0], (GLfloat)v[1], (GLfloat)v[2], 1.0f);
}

void GLAPIENTRY glTexCoord3i(GLint s, GLint t, GLint r)
{
	tgl_glTexCoord4f((GLfloat)s, (GLfloat)t, (GLfloat)r, 1.0f);
}
void GLAPIENTRY glTexCoord3iv(const GLint *v)
{
	tgl_glTexCoord4f((GLfloat)v[0], (GLfloat)v[1], (GLfloat)v[2], 1.0f);
}

void GLAPIENTRY glTexCoord3f(GLfloat s, GLfloat t, GLfloat r)
{
	tgl_glTexCoord4f(s, t, r, 1.0f);
}
void GLAPIENTRY glTexCoord3fv(const GLfloat *v)
{
	tgl_glTexCoord4f(v[0], v[1], v[2], 1.0f);
}

void GLAPIENTRY glTexCoord3d(GLdouble s, GLdouble t, GLdouble r)
{
	tgl_glTexCoord4f(s31_d2f(s), s31_d2f(t), s31_d2f(r), 1.0f);
}
void GLAPIENTRY glTexCoord3dv(const GLdouble *v)
{
	tgl_glTexCoord4f(s31_d2f(v[0]), s31_d2f(v[1]), s31_d2f(v[2]), 1.0f);
}

void GLAPIENTRY glTexCoord4s(GLshort s, GLshort t, GLshort r, GLshort q)
{
	tgl_glTexCoord4f((GLfloat)s, (GLfloat)t, (GLfloat)r, (GLfloat)q);
}
void GLAPIENTRY glTexCoord4sv(const GLshort *v)
{
	tgl_glTexCoord4f((GLfloat)v[0], (GLfloat)v[1], (GLfloat)v[2], (GLfloat)v[3]);
}

void GLAPIENTRY glTexCoord4i(GLint s, GLint t, GLint r, GLint q)
{
	tgl_glTexCoord4f((GLfloat)s, (GLfloat)t, (GLfloat)r, (GLfloat)q);
}
void GLAPIENTRY glTexCoord4iv(const GLint *v)
{
	tgl_glTexCoord4f((GLfloat)v[0], (GLfloat)v[1], (GLfloat)v[2], (GLfloat)v[3]);
}

void GLAPIENTRY glTexCoord4f(GLfloat s, GLfloat t, GLfloat r, GLfloat q)
{
	tgl_glTexCoord4f(s, t, r, q);
}
void GLAPIENTRY glTexCoord4fv(const GLfloat *v)
{
	tgl_glTexCoord4f(v[0], v[1], v[2], v[3]);
}

void GLAPIENTRY glTexCoord4d(GLdouble s, GLdouble t, GLdouble r, GLdouble q)
{
	tgl_glTexCoord4f(s31_d2f(s), s31_d2f(t), s31_d2f(r), s31_d2f(q));
}
void GLAPIENTRY glTexCoord4dv(const GLdouble *v)
{
	tgl_glTexCoord4f(s31_d2f(v[0]), s31_d2f(v[1]), s31_d2f(v[2]), s31_d2f(v[3]));
}

void GLAPIENTRY glMultiTexCoord1s(GLenum target, GLshort s)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f((GLfloat)s, 0.0f, 0.0f, 1.0f); else tgl_multi_tex_coord((int)target, (GLfloat)s, 0.0f, 0.0f, 1.0f);
}
void GLAPIENTRY glMultiTexCoord1sv(GLenum target, const GLshort *v)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f((GLfloat)v[0], 0.0f, 0.0f, 1.0f); else tgl_multi_tex_coord((int)target, (GLfloat)v[0], 0.0f, 0.0f, 1.0f);
}

void GLAPIENTRY glMultiTexCoord1i(GLenum target, GLint s)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f((GLfloat)s, 0.0f, 0.0f, 1.0f); else tgl_multi_tex_coord((int)target, (GLfloat)s, 0.0f, 0.0f, 1.0f);
}
void GLAPIENTRY glMultiTexCoord1iv(GLenum target, const GLint *v)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f((GLfloat)v[0], 0.0f, 0.0f, 1.0f); else tgl_multi_tex_coord((int)target, (GLfloat)v[0], 0.0f, 0.0f, 1.0f);
}

void GLAPIENTRY glMultiTexCoord1f(GLenum target, GLfloat s)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f(s, 0.0f, 0.0f, 1.0f); else tgl_multi_tex_coord((int)target, s, 0.0f, 0.0f, 1.0f);
}
void GLAPIENTRY glMultiTexCoord1fv(GLenum target, const GLfloat *v)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f(v[0], 0.0f, 0.0f, 1.0f); else tgl_multi_tex_coord((int)target, v[0], 0.0f, 0.0f, 1.0f);
}

void GLAPIENTRY glMultiTexCoord1d(GLenum target, GLdouble s)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f(s31_d2f(s), 0.0f, 0.0f, 1.0f); else tgl_multi_tex_coord((int)target, s31_d2f(s), 0.0f, 0.0f, 1.0f);
}
void GLAPIENTRY glMultiTexCoord1dv(GLenum target, const GLdouble *v)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f(s31_d2f(v[0]), 0.0f, 0.0f, 1.0f); else tgl_multi_tex_coord((int)target, s31_d2f(v[0]), 0.0f, 0.0f, 1.0f);
}

void GLAPIENTRY glMultiTexCoord2s(GLenum target, GLshort s, GLshort t)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f((GLfloat)s, (GLfloat)t, 0.0f, 1.0f); else tgl_multi_tex_coord((int)target, (GLfloat)s, (GLfloat)t, 0.0f, 1.0f);
}
void GLAPIENTRY glMultiTexCoord2sv(GLenum target, const GLshort *v)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f((GLfloat)v[0], (GLfloat)v[1], 0.0f, 1.0f); else tgl_multi_tex_coord((int)target, (GLfloat)v[0], (GLfloat)v[1], 0.0f, 1.0f);
}

void GLAPIENTRY glMultiTexCoord2i(GLenum target, GLint s, GLint t)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f((GLfloat)s, (GLfloat)t, 0.0f, 1.0f); else tgl_multi_tex_coord((int)target, (GLfloat)s, (GLfloat)t, 0.0f, 1.0f);
}
void GLAPIENTRY glMultiTexCoord2iv(GLenum target, const GLint *v)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f((GLfloat)v[0], (GLfloat)v[1], 0.0f, 1.0f); else tgl_multi_tex_coord((int)target, (GLfloat)v[0], (GLfloat)v[1], 0.0f, 1.0f);
}

void GLAPIENTRY glMultiTexCoord2f(GLenum target, GLfloat s, GLfloat t)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f(s, t, 0.0f, 1.0f); else tgl_multi_tex_coord((int)target, s, t, 0.0f, 1.0f);
}
void GLAPIENTRY glMultiTexCoord2fv(GLenum target, const GLfloat *v)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f(v[0], v[1], 0.0f, 1.0f); else tgl_multi_tex_coord((int)target, v[0], v[1], 0.0f, 1.0f);
}

void GLAPIENTRY glMultiTexCoord2d(GLenum target, GLdouble s, GLdouble t)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f(s31_d2f(s), s31_d2f(t), 0.0f, 1.0f); else tgl_multi_tex_coord((int)target, s31_d2f(s), s31_d2f(t), 0.0f, 1.0f);
}
void GLAPIENTRY glMultiTexCoord2dv(GLenum target, const GLdouble *v)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f(s31_d2f(v[0]), s31_d2f(v[1]), 0.0f, 1.0f); else tgl_multi_tex_coord((int)target, s31_d2f(v[0]), s31_d2f(v[1]), 0.0f, 1.0f);
}

void GLAPIENTRY glMultiTexCoord3s(GLenum target, GLshort s, GLshort t, GLshort r)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f((GLfloat)s, (GLfloat)t, (GLfloat)r, 1.0f); else tgl_multi_tex_coord((int)target, (GLfloat)s, (GLfloat)t, (GLfloat)r, 1.0f);
}
void GLAPIENTRY glMultiTexCoord3sv(GLenum target, const GLshort *v)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f((GLfloat)v[0], (GLfloat)v[1], (GLfloat)v[2], 1.0f); else tgl_multi_tex_coord((int)target, (GLfloat)v[0], (GLfloat)v[1], (GLfloat)v[2], 1.0f);
}

void GLAPIENTRY glMultiTexCoord3i(GLenum target, GLint s, GLint t, GLint r)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f((GLfloat)s, (GLfloat)t, (GLfloat)r, 1.0f); else tgl_multi_tex_coord((int)target, (GLfloat)s, (GLfloat)t, (GLfloat)r, 1.0f);
}
void GLAPIENTRY glMultiTexCoord3iv(GLenum target, const GLint *v)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f((GLfloat)v[0], (GLfloat)v[1], (GLfloat)v[2], 1.0f); else tgl_multi_tex_coord((int)target, (GLfloat)v[0], (GLfloat)v[1], (GLfloat)v[2], 1.0f);
}

void GLAPIENTRY glMultiTexCoord3f(GLenum target, GLfloat s, GLfloat t, GLfloat r)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f(s, t, r, 1.0f); else tgl_multi_tex_coord((int)target, s, t, r, 1.0f);
}
void GLAPIENTRY glMultiTexCoord3fv(GLenum target, const GLfloat *v)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f(v[0], v[1], v[2], 1.0f); else tgl_multi_tex_coord((int)target, v[0], v[1], v[2], 1.0f);
}

void GLAPIENTRY glMultiTexCoord3d(GLenum target, GLdouble s, GLdouble t, GLdouble r)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f(s31_d2f(s), s31_d2f(t), s31_d2f(r), 1.0f); else tgl_multi_tex_coord((int)target, s31_d2f(s), s31_d2f(t), s31_d2f(r), 1.0f);
}
void GLAPIENTRY glMultiTexCoord3dv(GLenum target, const GLdouble *v)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f(s31_d2f(v[0]), s31_d2f(v[1]), s31_d2f(v[2]), 1.0f); else tgl_multi_tex_coord((int)target, s31_d2f(v[0]), s31_d2f(v[1]), s31_d2f(v[2]), 1.0f);
}

void GLAPIENTRY glMultiTexCoord4s(GLenum target, GLshort s, GLshort t, GLshort r, GLshort q)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f((GLfloat)s, (GLfloat)t, (GLfloat)r, (GLfloat)q); else tgl_multi_tex_coord((int)target, (GLfloat)s, (GLfloat)t, (GLfloat)r, (GLfloat)q);
}
void GLAPIENTRY glMultiTexCoord4sv(GLenum target, const GLshort *v)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f((GLfloat)v[0], (GLfloat)v[1], (GLfloat)v[2], (GLfloat)v[3]); else tgl_multi_tex_coord((int)target, (GLfloat)v[0], (GLfloat)v[1], (GLfloat)v[2], (GLfloat)v[3]);
}

void GLAPIENTRY glMultiTexCoord4i(GLenum target, GLint s, GLint t, GLint r, GLint q)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f((GLfloat)s, (GLfloat)t, (GLfloat)r, (GLfloat)q); else tgl_multi_tex_coord((int)target, (GLfloat)s, (GLfloat)t, (GLfloat)r, (GLfloat)q);
}
void GLAPIENTRY glMultiTexCoord4iv(GLenum target, const GLint *v)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f((GLfloat)v[0], (GLfloat)v[1], (GLfloat)v[2], (GLfloat)v[3]); else tgl_multi_tex_coord((int)target, (GLfloat)v[0], (GLfloat)v[1], (GLfloat)v[2], (GLfloat)v[3]);
}

void GLAPIENTRY glMultiTexCoord4f(GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f(s, t, r, q); else tgl_multi_tex_coord((int)target, s, t, r, q);
}
void GLAPIENTRY glMultiTexCoord4fv(GLenum target, const GLfloat *v)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f(v[0], v[1], v[2], v[3]); else tgl_multi_tex_coord((int)target, v[0], v[1], v[2], v[3]);
}

void GLAPIENTRY glMultiTexCoord4d(GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f(s31_d2f(s), s31_d2f(t), s31_d2f(r), s31_d2f(q)); else tgl_multi_tex_coord((int)target, s31_d2f(s), s31_d2f(t), s31_d2f(r), s31_d2f(q));
}
void GLAPIENTRY glMultiTexCoord4dv(GLenum target, const GLdouble *v)
{
	if (target == GL_TEXTURE0) tgl_glTexCoord4f(s31_d2f(v[0]), s31_d2f(v[1]), s31_d2f(v[2]), s31_d2f(v[3])); else tgl_multi_tex_coord((int)target, s31_d2f(v[0]), s31_d2f(v[1]), s31_d2f(v[2]), s31_d2f(v[3]));
}

void GLAPIENTRY glMultiTexCoord1sARB(GLenum target, GLshort s) __attribute__((alias("glMultiTexCoord1s")));
void GLAPIENTRY glMultiTexCoord1svARB(GLenum target, const GLshort *v) __attribute__((alias("glMultiTexCoord1sv")));
void GLAPIENTRY glMultiTexCoord1iARB(GLenum target, GLint s) __attribute__((alias("glMultiTexCoord1i")));
void GLAPIENTRY glMultiTexCoord1ivARB(GLenum target, const GLint *v) __attribute__((alias("glMultiTexCoord1iv")));
void GLAPIENTRY glMultiTexCoord1fARB(GLenum target, GLfloat s) __attribute__((alias("glMultiTexCoord1f")));
void GLAPIENTRY glMultiTexCoord1fvARB(GLenum target, const GLfloat *v) __attribute__((alias("glMultiTexCoord1fv")));
void GLAPIENTRY glMultiTexCoord1dARB(GLenum target, GLdouble s) __attribute__((alias("glMultiTexCoord1d")));
void GLAPIENTRY glMultiTexCoord1dvARB(GLenum target, const GLdouble *v) __attribute__((alias("glMultiTexCoord1dv")));
void GLAPIENTRY glMultiTexCoord2sARB(GLenum target, GLshort s, GLshort t) __attribute__((alias("glMultiTexCoord2s")));
void GLAPIENTRY glMultiTexCoord2svARB(GLenum target, const GLshort *v) __attribute__((alias("glMultiTexCoord2sv")));
void GLAPIENTRY glMultiTexCoord2iARB(GLenum target, GLint s, GLint t) __attribute__((alias("glMultiTexCoord2i")));
void GLAPIENTRY glMultiTexCoord2ivARB(GLenum target, const GLint *v) __attribute__((alias("glMultiTexCoord2iv")));
void GLAPIENTRY glMultiTexCoord2fARB(GLenum target, GLfloat s, GLfloat t) __attribute__((alias("glMultiTexCoord2f")));
void GLAPIENTRY glMultiTexCoord2fvARB(GLenum target, const GLfloat *v) __attribute__((alias("glMultiTexCoord2fv")));
void GLAPIENTRY glMultiTexCoord2dARB(GLenum target, GLdouble s, GLdouble t) __attribute__((alias("glMultiTexCoord2d")));
void GLAPIENTRY glMultiTexCoord2dvARB(GLenum target, const GLdouble *v) __attribute__((alias("glMultiTexCoord2dv")));
void GLAPIENTRY glMultiTexCoord3sARB(GLenum target, GLshort s, GLshort t, GLshort r) __attribute__((alias("glMultiTexCoord3s")));
void GLAPIENTRY glMultiTexCoord3svARB(GLenum target, const GLshort *v) __attribute__((alias("glMultiTexCoord3sv")));
void GLAPIENTRY glMultiTexCoord3iARB(GLenum target, GLint s, GLint t, GLint r) __attribute__((alias("glMultiTexCoord3i")));
void GLAPIENTRY glMultiTexCoord3ivARB(GLenum target, const GLint *v) __attribute__((alias("glMultiTexCoord3iv")));
void GLAPIENTRY glMultiTexCoord3fARB(GLenum target, GLfloat s, GLfloat t, GLfloat r) __attribute__((alias("glMultiTexCoord3f")));
void GLAPIENTRY glMultiTexCoord3fvARB(GLenum target, const GLfloat *v) __attribute__((alias("glMultiTexCoord3fv")));
void GLAPIENTRY glMultiTexCoord3dARB(GLenum target, GLdouble s, GLdouble t, GLdouble r) __attribute__((alias("glMultiTexCoord3d")));
void GLAPIENTRY glMultiTexCoord3dvARB(GLenum target, const GLdouble *v) __attribute__((alias("glMultiTexCoord3dv")));
void GLAPIENTRY glMultiTexCoord4sARB(GLenum target, GLshort s, GLshort t, GLshort r, GLshort q) __attribute__((alias("glMultiTexCoord4s")));
void GLAPIENTRY glMultiTexCoord4svARB(GLenum target, const GLshort *v) __attribute__((alias("glMultiTexCoord4sv")));
void GLAPIENTRY glMultiTexCoord4iARB(GLenum target, GLint s, GLint t, GLint r, GLint q) __attribute__((alias("glMultiTexCoord4i")));
void GLAPIENTRY glMultiTexCoord4ivARB(GLenum target, const GLint *v) __attribute__((alias("glMultiTexCoord4iv")));
void GLAPIENTRY glMultiTexCoord4fARB(GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q) __attribute__((alias("glMultiTexCoord4f")));
void GLAPIENTRY glMultiTexCoord4fvARB(GLenum target, const GLfloat *v) __attribute__((alias("glMultiTexCoord4fv")));
void GLAPIENTRY glMultiTexCoord4dARB(GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q) __attribute__((alias("glMultiTexCoord4d")));
void GLAPIENTRY glMultiTexCoord4dvARB(GLenum target, const GLdouble *v) __attribute__((alias("glMultiTexCoord4dv")));

void GLAPIENTRY glRects(GLshort x1, GLshort y1, GLshort x2, GLshort y2)
{
	GLfloat a = (GLfloat)x1, b = (GLfloat)y1, c = (GLfloat)x2, d = (GLfloat)y2;
	tgl_glBegin(GL_POLYGON);
	tgl_glVertex4f(a, b, 0.0f, 1.0f);
	tgl_glVertex4f(c, b, 0.0f, 1.0f);
	tgl_glVertex4f(c, d, 0.0f, 1.0f);
	tgl_glVertex4f(a, d, 0.0f, 1.0f);
	tgl_glEnd();
}
void GLAPIENTRY glRectsv(const GLshort *v1, const GLshort *v2)
{
	GLfloat a = (GLfloat)v1[0], b = (GLfloat)v1[1], c = (GLfloat)v2[0], d = (GLfloat)v2[1];
	tgl_glBegin(GL_POLYGON);
	tgl_glVertex4f(a, b, 0.0f, 1.0f);
	tgl_glVertex4f(c, b, 0.0f, 1.0f);
	tgl_glVertex4f(c, d, 0.0f, 1.0f);
	tgl_glVertex4f(a, d, 0.0f, 1.0f);
	tgl_glEnd();
}

void GLAPIENTRY glRecti(GLint x1, GLint y1, GLint x2, GLint y2)
{
	GLfloat a = (GLfloat)x1, b = (GLfloat)y1, c = (GLfloat)x2, d = (GLfloat)y2;
	tgl_glBegin(GL_POLYGON);
	tgl_glVertex4f(a, b, 0.0f, 1.0f);
	tgl_glVertex4f(c, b, 0.0f, 1.0f);
	tgl_glVertex4f(c, d, 0.0f, 1.0f);
	tgl_glVertex4f(a, d, 0.0f, 1.0f);
	tgl_glEnd();
}
void GLAPIENTRY glRectiv(const GLint *v1, const GLint *v2)
{
	GLfloat a = (GLfloat)v1[0], b = (GLfloat)v1[1], c = (GLfloat)v2[0], d = (GLfloat)v2[1];
	tgl_glBegin(GL_POLYGON);
	tgl_glVertex4f(a, b, 0.0f, 1.0f);
	tgl_glVertex4f(c, b, 0.0f, 1.0f);
	tgl_glVertex4f(c, d, 0.0f, 1.0f);
	tgl_glVertex4f(a, d, 0.0f, 1.0f);
	tgl_glEnd();
}

void GLAPIENTRY glRectf(GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2)
{
	GLfloat a = x1, b = y1, c = x2, d = y2;
	tgl_glBegin(GL_POLYGON);
	tgl_glVertex4f(a, b, 0.0f, 1.0f);
	tgl_glVertex4f(c, b, 0.0f, 1.0f);
	tgl_glVertex4f(c, d, 0.0f, 1.0f);
	tgl_glVertex4f(a, d, 0.0f, 1.0f);
	tgl_glEnd();
}
void GLAPIENTRY glRectfv(const GLfloat *v1, const GLfloat *v2)
{
	GLfloat a = v1[0], b = v1[1], c = v2[0], d = v2[1];
	tgl_glBegin(GL_POLYGON);
	tgl_glVertex4f(a, b, 0.0f, 1.0f);
	tgl_glVertex4f(c, b, 0.0f, 1.0f);
	tgl_glVertex4f(c, d, 0.0f, 1.0f);
	tgl_glVertex4f(a, d, 0.0f, 1.0f);
	tgl_glEnd();
}

void GLAPIENTRY glRectd(GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2)
{
	GLfloat a = s31_d2f(x1), b = s31_d2f(y1), c = s31_d2f(x2), d = s31_d2f(y2);
	tgl_glBegin(GL_POLYGON);
	tgl_glVertex4f(a, b, 0.0f, 1.0f);
	tgl_glVertex4f(c, b, 0.0f, 1.0f);
	tgl_glVertex4f(c, d, 0.0f, 1.0f);
	tgl_glVertex4f(a, d, 0.0f, 1.0f);
	tgl_glEnd();
}
void GLAPIENTRY glRectdv(const GLdouble *v1, const GLdouble *v2)
{
	GLfloat a = s31_d2f(v1[0]), b = s31_d2f(v1[1]), c = s31_d2f(v2[0]), d = s31_d2f(v2[1]);
	tgl_glBegin(GL_POLYGON);
	tgl_glVertex4f(a, b, 0.0f, 1.0f);
	tgl_glVertex4f(c, b, 0.0f, 1.0f);
	tgl_glVertex4f(c, d, 0.0f, 1.0f);
	tgl_glVertex4f(a, d, 0.0f, 1.0f);
	tgl_glEnd();
}

void GLAPIENTRY glIndexs(GLshort c) { (void)c; }
void GLAPIENTRY glIndexsv(const GLshort *c) { (void)c; }
void GLAPIENTRY glIndexi(GLint c) { (void)c; }
void GLAPIENTRY glIndexiv(const GLint *c) { (void)c; }
void GLAPIENTRY glIndexf(GLfloat c) { (void)c; }
void GLAPIENTRY glIndexfv(const GLfloat *c) { (void)c; }
void GLAPIENTRY glIndexd(GLdouble c) { (void)c; }
void GLAPIENTRY glIndexdv(const GLdouble *c) { (void)c; }
void GLAPIENTRY glIndexub(GLubyte c) { (void)c; }
void GLAPIENTRY glIndexubv(const GLubyte *c) { (void)c; }

void GLAPIENTRY glEdgeFlag(GLboolean flag) { tgl_glEdgeFlag(flag != 0); }
void GLAPIENTRY glEdgeFlagv(const GLboolean *flag) { tgl_glEdgeFlag(*flag != 0); }
