#!/usr/bin/env python3
"""Generate gl_attrib.c: every GL 1.3 per-vertex attribute entry point
(glVertex*, glNormal*, glColor*, glTexCoord*, glMultiTexCoord*, glRect*,
glIndex*, glEdgeFlag*) as a conversion to float plus one call into TinyGL.

Run from gl/api:  python3 mkattrib.py > gl_attrib.c
The output is committed; rerun only when the rules below change.

Conversions follow the GL 1.3 spec, table 2.9: colours and normals given
as integers are normalised (signed: (2c+1)/(2^b-1), unsigned: c/(2^b-1));
coordinates are converted directly. Doubles go through s31_d2f(), a few
integer instructions instead of libgcc's __truncdfsf2.
"""

T = {  # suffix: (C type, signed?, bits)
    'b': ('GLbyte', True, 8), 'ub': ('GLubyte', False, 8),
    's': ('GLshort', True, 16), 'us': ('GLushort', False, 16),
    'i': ('GLint', True, 32), 'ui': ('GLuint', False, 32),
    'f': ('GLfloat', None, 0), 'd': ('GLdouble', None, 0),
}

def conv(sfx, x, norm):
    ctype, signed, bits = T[sfx]
    if sfx == 'f':
        return x
    if sfx == 'd':
        return 's31_d2f(%s)' % x
    if not norm:
        return '(GLfloat)%s' % x
    if bits == 32:
        # float has 24 bits of mantissa: scale in float, exactly as Mesa does
        if signed:
            return '((2.0f * (GLfloat)%s + 1.0f) * (1.0f / 4294967295.0f))' % x
        return '((GLfloat)%s * (1.0f / 4294967295.0f))' % x
    full = (1 << bits) - 1
    if signed:
        return '((2 * (GLint)%s + 1) * (1.0f / %d.0f))' % (x, full)
    return '((GLfloat)%s * (1.0f / %d.0f))' % (x, full)

out = []
w = out.append
w('/* GENERATED by mkattrib.py - do not edit; see that script. s31, MIT. */')
w('#include "s31_api.h"')
w('')

def fam(name, counts, sfxs, call, norm, fill, extra_first=''):
    """name: e.g. 'Vertex'; call(vals) -> C statement; fill: defaults."""
    for n in counts:
        for sfx in sfxs:
            ctype = T[sfx][0]
            args = {'Vertex': 'xyzw', 'Color': 'rgba', 'Normal': 'xyz',
                    'TexCoord': 'strq', 'MultiTexCoord': 'strq'}[name]
            a = list(args[:n])
            pre = extra_first
            params = ', '.join(['%s %s' % (ctype, v) for v in a])
            if pre:
                params = pre + (', ' + params if params else '')
            vals = [conv(sfx, v, norm) for v in a] + fill[n:]
            w('void GLAPIENTRY gl%s%d%s(%s)' % (name, n, sfx, params))
            w('{')
            w('\t' + call(vals))
            w('}')
            vp = [conv(sfx, 'v[%d]' % i, norm) for i in range(n)] + fill[n:]
            vparams = 'const %s *v' % ctype
            if pre:
                vparams = pre + ', ' + vparams
            w('void GLAPIENTRY gl%s%d%sv(%s)' % (name, n, sfx, vparams))
            w('{')
            w('\t' + call(vp))
            w('}')
            w('')

# glVertex{234}{sifd}[v]
fam('Vertex', [2, 3, 4], ['s', 'i', 'f', 'd'],
    lambda v: 'tgl_glVertex4f(%s);' % ', '.join(v), False,
    ['0', '0', '0.0f', '1.0f'])
# glNormal3{bsifd}[v]
fam('Normal', [3], ['b', 's', 'i', 'f', 'd'],
    lambda v: 'tgl_glNormal3f(%s);' % ', '.join(v[:3]), True, ['0', '0', '0'])
# glColor{34}{b,s,i,f,d,ub,us,ui}[v]
fam('Color', [3, 4], ['b', 's', 'i', 'f', 'd', 'ub', 'us', 'ui'],
    lambda v: 'tgl_glColor4f(%s);' % ', '.join(v), True,
    ['0', '0', '0', '1.0f'])
# glTexCoord{1234}{sifd}[v]
fam('TexCoord', [1, 2, 3, 4], ['s', 'i', 'f', 'd'],
    lambda v: 'tgl_glTexCoord4f(%s);' % ', '.join(v), False,
    ['0', '0.0f', '0.0f', '1.0f'])
# glMultiTexCoord{1234}{sifd}[v](target, ...): one unit
fam('MultiTexCoord', [1, 2, 3, 4], ['s', 'i', 'f', 'd'],
    lambda v: 'if (target == GL_TEXTURE0) tgl_glTexCoord4f(%s); '
              'else if (target < GL_TEXTURE0 || target > GL_TEXTURE0 + 31) '
              'S31_ERR(GL_INVALID_ENUM);' % ', '.join(v),
    False, ['0', '0.0f', '0.0f', '1.0f'], extra_first='GLenum target')

# ARB aliases of the multitexture coordinates (GL_ARB_multitexture, gl.h)
for n in [1, 2, 3, 4]:
    for sfx in ['s', 'i', 'f', 'd']:
        for v in ['', 'v']:
            base = 'glMultiTexCoord%d%s%s' % (n, sfx, v)
            ctype = T[sfx][0]
            if v:
                params = 'GLenum target, const %s *v' % ctype
            else:
                params = 'GLenum target, ' + ', '.join(
                    '%s %s' % (ctype, a) for a in 'strq'[:n])
            w('void GLAPIENTRY %sARB(%s) __attribute__((alias("%s")));'
              % (base, params, base))
w('')

# glRect{sifd}[v]: GL 1.3 section 2.9
for sfx in ['s', 'i', 'f', 'd']:
    ctype = T[sfx][0]
    c = lambda x: conv(sfx, x, False)
    body = ('\tGLfloat a = %s, b = %s, c = %s, d = %s;\n'
            '\ttgl_glBegin(GL_POLYGON);\n'
            '\ttgl_glVertex4f(a, b, 0.0f, 1.0f);\n'
            '\ttgl_glVertex4f(c, b, 0.0f, 1.0f);\n'
            '\ttgl_glVertex4f(c, d, 0.0f, 1.0f);\n'
            '\ttgl_glVertex4f(a, d, 0.0f, 1.0f);\n'
            '\ttgl_glEnd();')
    w('void GLAPIENTRY glRect%s(%s x1, %s y1, %s x2, %s y2)' % ((sfx,) + (ctype,) * 4))
    w('{')
    w(body % (c('x1'), c('y1'), c('x2'), c('y2')))
    w('}')
    w('void GLAPIENTRY glRect%sv(const %s *v1, const %s *v2)' % (sfx, ctype, ctype))
    w('{')
    w(body % (c('v1[0]'), c('v1[1]'), c('v2[0]'), c('v2[1]')))
    w('}')
    w('')

# glIndex*: RGBA mode only, so the colour index has no effect (GL 1.3 2.7)
for sfx, ctype in [('s', 'GLshort'), ('i', 'GLint'), ('f', 'GLfloat'),
                   ('d', 'GLdouble'), ('ub', 'GLubyte')]:
    w('void GLAPIENTRY glIndex%s(%s c) { (void)c; }' % (sfx, ctype))
    w('void GLAPIENTRY glIndex%sv(const %s *c) { (void)c; }' % (sfx, ctype))
w('')

w('void GLAPIENTRY glEdgeFlag(GLboolean flag) { tgl_glEdgeFlag(flag != 0); }')
w('void GLAPIENTRY glEdgeFlagv(const GLboolean *flag) { tgl_glEdgeFlag(*flag != 0); }')

print('\n'.join(out))
