#!/usr/bin/env python3
"""Generate the libGL export surface that is not really implemented, and the
glXGetProcAddress table of what is (the rows procs.c includes).

usage: mkstubs.py GL/gl.h GL/glext.h implemented.txt gen_stubs.c gen_procs.inc

implemented.txt: the gl* symbols the ABI-layer objects define (the build
scripts take them from nm), so the table follows the code automatically.

Exported, per plan F1 (docs/gl-plan-2026-09-25.md section 2.2):
  - every GL 1.0-1.3 entry point in gl.h, and GL_ARB_multitexture;
  - every GL 1.4, 1.5 and 2.0 name in glext.h: musl binds eagerly, so one
    missing import stops a stock binary at load time;
  - the EXT names below that old binaries built against Mesa import.
NOT exported, per plan 4.2 (the SDL2 regression guard): glBlendEquation,
glBlendFuncSeparate and their EXT/ATI/2.0-separate variants.

Stub behaviour: prints "libGL: unimplemented <name>" once per name, never per
call, and never aborts. GL 1.5/2.0 object APIs (buffers, queries, shaders)
and queries that cannot fill their output record GL_INVALID_OPERATION; the
remaining fixed-function calls are silent no-ops. Value-returning stubs
return 0 (NULL, GL_FALSE), and *Location stubs -1 ("not found").
s31gl_get_proc() never returns a stub.
"""
import re
import sys

EXCLUDE = {
    'glBlendEquation', 'glBlendFuncSeparate', 'glBlendEquationSeparate',
    'glBlendEquationEXT', 'glBlendFuncSeparateEXT',
    'glBlendEquationSeparateEXT', 'glBlendEquationSeparateATI',
    'glBlendFuncSeparateINGR',
}
GLEXT_SECTIONS = {'GL_VERSION_1_4', 'GL_VERSION_1_5', 'GL_VERSION_2_0',
                  'GL_EXT_texture_object', 'GL_EXT_vertex_array',
                  'GL_EXT_compiled_vertex_array', 'GL_EXT_polygon_offset',
                  'GL_EXT_draw_range_elements'}


def parse(path, want_section):
    """[(name, ret, args, section)] for GLAPI prototypes in path."""
    out = []
    sec = None
    buf = ''
    lines = open(path).read().split('\n')
    lineno_of_version = {}
    for i, ln in enumerate(lines, 1):
        m = re.match(r'#ifndef\s+(GL_\w+)\s*$', ln)
        if m and not m.group(1).startswith('GL_GLEXT') and \
           not m.group(1).startswith('GLAPI'):
            sec = m.group(1)
        if 'GLAPI' in ln and not ln.lstrip().startswith('#') or buf:
            buf += ln + ' '
            if ';' in ln:
                m = re.match(r'\s*GLAPI\s+(.*?)\s*(?:GLAPIENTRY|APIENTRY)\s+'
                             r'(gl\w+)\s*\((.*)\)\s*;', buf)
                if m and want_section(sec, i):
                    out.append((m.group(2), m.group(1).strip(),
                                m.group(3).strip(), sec))
                buf = ''
    return out


def glh_section(path):
    """gl.h has no per-version guards; the OpenGL 1.2 / 1.3 comments and
    the GL_ARB_multitexture guard delimit them."""
    txt = open(path).read().split('\n')
    marks = {}
    for i, ln in enumerate(txt, 1):
        if 'OpenGL 1.2' in ln and '12' not in marks:
            marks['12'] = i
        if 'OpenGL 1.3' in ln and '13' not in marks:
            marks['13'] = i
        if ln.startswith('#endif /* GL_ARB_multitexture */'):
            marks['end'] = i
    return marks


def main():
    glh, glext, impl_path, stubs_out, procs_out = sys.argv[1:6]
    impl = set(open(impl_path).read().split())
    marks = glh_section(glh)
    core = parse(glh, lambda sec, i: i <= marks['end'])
    ext = parse(glext, lambda sec, i: sec in GLEXT_SECTIONS)
    exports = {}
    for name, ret, args, sec in core + ext:
        if name in EXCLUDE or name in exports:
            continue
        exports[name] = (ret, args, sec)

    # ---- stubs ----
    s = []
    w = s.append
    w('/* GENERATED by mkstubs.py at build time - do not edit. s31, MIT. */')
    w('#include "s31_api.h"')
    w('')
    w('static void unimpl(const char *name) { s31_unimpl(name); }')
    w('')
    nstub = 0
    for name in sorted(exports):
        if name in impl:
            continue
        ret, args, sec = exports[name]
        # parameter list must have names; the headers always give them
        err = (sec in ('GL_VERSION_1_5', 'GL_VERSION_2_0') or
               name.startswith('glGet') or name in (
                   'glReadPixels', 'glFeedbackBuffer', 'glCompressedTexImage1D',
                   'glCompressedTexImage2D', 'glCompressedTexImage3D',
                   'glCompressedTexSubImage1D', 'glCompressedTexSubImage2D',
                   'glCompressedTexSubImage3D', 'glTexImage3D',
                   'glTexSubImage3D', 'glCopyTexSubImage3D'))
        w('%s GLAPIENTRY %s(%s)' % (ret, name, args))
        w('{')
        w('\tstatic int warned;')
        w('\tif (!warned) { warned = 1; unimpl("%s"); }' % name)
        if err:
            w('\tS31_ERR(GL_INVALID_OPERATION);')
        if ret != 'void':
            if 'Location' in name and ret == 'GLint':
                w('\treturn -1;')
            elif '*' in ret:
                w('\treturn 0;')
            else:
                w('\treturn (%s)0;' % ret)
        w('}')
        w('')
        nstub += 1

    # ---- procs.c table rows: only what is really implemented ----
    p = []
    w = p.append
    w('/* GENERATED by mkstubs.py at build time - do not edit. Rows of the')
    w(' * table in procs.c: implemented entry points only, sorted by strcmp. */')
    names = sorted((n for n in impl if n in exports), key=lambda x: x.encode())
    for n in names:
        w('\t{ "%s", (void *)%s },' % (n, n))

    open(stubs_out, 'w').write('\n'.join(s) + '\n')
    open(procs_out, 'w').write('\n'.join(p) + '\n')
    extra = sorted(n for n in impl if n not in exports)
    print('mkstubs: %d exported GL names: %d implemented, %d stubs'
          % (len(exports), len(exports) - nstub, nstub))
    if extra:
        print('mkstubs: implemented but not in the export list: %s' % ' '.join(extra))


main()
